name: Trading
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pytest
    - tqdm
    - pytorch
    - numpy
    - pandas
    - polars
    - ta-lib
    - pillow
    - jupyter
    - psycopg2
    - matplotlib
    - xlwings
    - yfinance
    - dash
    - dash-bootstrap-components
