name: Trading
channels:
    - bloomberg
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.12
    - pip
    # --- Utils & Core ---
    - tqdm
    - wheel
    - pytest
    - setuptools
    # --- Data Science & Visualization ---
    - numpy
    - pandas
    - polars
    - panel
    - bokeh
    - altair
    - hvplot
    - seaborn
    - holoviews
    - matplotlib
    # --- Automation & Jupyter ---
    - pillow
    - selenium
    - jupyter
    - notebook
    - ipykernel
    - ipywidgets
    # --- Database Drivers ---
    - pymssql
    - oracledb
    - psycopg2-binary
    # --- Finance Drivers ---
    - ta-lib
    - blpapi
    - xlwings
    - yfinance
    # --- Web Frameworks ---
    - dash
    - dash-extensions
    - dash-bootstrap-components
    - fastapi
    - flask
    # --- Machine Learning & AI ---
    - pytorch
    - torchaudio
    - torchvision
    - gymnasium