name: Trading
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - pytest
    - numpy
    - pandas
    - polars
    - matplotlib
    - pytorch
    - tqdm
    - pillow
    - ta-lib
    - jupyter
    - psycopg[binary,pool]
    - xlwings
    - yfinance
    - dash
    - dash-bootstrap-components
