name: Quant
channels:
    - defaults
    - conda-forge
    - bloomberg
    - pytorch
dependencies:
    - python=3.12
    - pip

    - tqdm
    - wheel
    - pytest
    - setuptools

    - numpy
    - pandas
    - polars
    - panel
    - bokeh
    - altair
    - hvplot
    - seaborn
    - holoviews
    - matplotlib

    - pillow
    - selenium
    - jupyter
    - notebook
    - ipykernel
    - ipywidgets

    - pymssql
    - oracledb
    - psycopg[c]

    - ta-lib
    - blpapi
    - xlwings
    - yfinance

    - dash
    - dash-extensions
    - dash-bootstrap-components
    - fastapi
    - flask

    - pytorch
    - torchaudio
    - torchvision
    - gymnasium