name: Trading
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pip:
        - tqdm
        - wheel
        - pytest
        - setuptools

        - numpy
        - pandas
        - polars
        - panel
        - bokeh
        - altair
        - seaborn
        - holoviews
        - matplotlib
        - selenium

        - jupyter
        - notebook
        - ipykernel
        - ipywidgets

        - pillow
        - pytorch
        - pymssql
        - oracledb
        - psycopg[binary]

        - ta-lib
        - blpapi
        - xlwings
        - yfinance

        - dash
        - dash-boostrap-templates
        - dash-bootstrap-components
        - dash-extensions
        - fastapi
        - flask
