name: Trading
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pip:
        - tqdm
        - wheel
        - pytest
        - setuptools

        - numpy
        - pandas
        - polars
        - panel
        - bokeh
        - altair
        - seaborn
        - holoviews
        - matplotlib

        - pillow
        - selenium

        - jupyter
        - notebook
        - ipykernel
        - ipywidgets

        - pymssql
        - oracledb
        - psycopg[binary]

        - ta-lib
        - blpapi
        - xlwings
        - yfinance

        - dash
        - dash-extensions
        - dash-bootstrap-components
        - fastapi
        - flask

        - torch
        - torchaudio
        - torchvision
        - gymnasium
