name: Trading
channels:
    - defaults
    - conda-forge
dependencies:
    - tqdm
    - pytorch
    - attrs
    - numpy
    - pandas
    - polars
    - ta-lib
    - pillow
    - jupyter
    - psycopg2
    - matplotlib
    - xlwings
    - yfinance
