import pytest
from Library.Database.Postgres.Postgres import PostgresDatabaseAPI
from Library.Database.Query import QueryAPI
from Library.Universe import CategoryAPI, ProviderAPI, TickerAPI, Provider, Platform, SecurityAPI, ContractAPI, TimeframeAPI
from Library.Database.Datapoint import DatapointAPI

def test_populate_universe(db):
    by = "Population"
    categories = [
        ("Forex (Major)", "Forex", "Major", "Currency"),
        ("Forex (Minor)", "Forex", "Minor", "Currency"),
        ("Forex (Exotic)", "Forex", "Exotic", "Currency"),
        ("Index (AMER) Equity", "Index", "AMER", "Equity"),
        ("Index (EMEA) Equity", "Index", "EMEA", "Equity"),
        ("Index (APAC) Equity", "Index", "APAC", "Equity"),
        ("Index (AMER) Currency", "Index", "AMER", "Currency"),
        ("Index (EMEA) Currency", "Index", "EMEA", "Currency"),
        ("Index (APAC) Currency", "Index", "APAC", "Currency"),
        ("Crypto (Major)", "Crypto", "Major", "Currency"),
        ("Crypto (Minor)", "Crypto", "Minor", "Currency"),
        ("Crypto (Exotic)", "Crypto", "Exotic", "Currency"),
        ("Metal (Major)", "Metal", "Major", "Commodity"),
        ("Metal (Minor)", "Metal", "Minor", "Commodity"),
        ("Energy (Major)", "Energy", "Major", "Commodity"),
        ("Energy (Minor)", "Energy", "Minor", "Commodity"),
        ("Stock (US)", "Stock", "US", "Equity"),
        ("ETF (US)", "ETF", "US", "Equity")
    ]
    for uid, primary, secondary, alt in categories:
        cat = CategoryAPI(UID=uid, Primary=primary, Secondary=secondary, Alternative=alt, db=db)
        cat.push(by=by)
    provider_map = {
        Provider.Spotware: "Spotware Systems",
        Provider.Pepperstone: "Pepperstone Europe",
        Provider.ICMarkets: "IC Markets EU Ltd",
        Provider.Bloomberg: "Bloomberg",
        Provider.Yahoo: "Yahoo Finance"
    }
    for p in Provider:
        name = provider_map[p]
        abbrev = p.name
        uid = f"{abbrev} ({Platform.cTrader.name})"
        provider = ProviderAPI(UID=uid, Platform=Platform.cTrader, Name=name, Abbreviation=abbrev, db=db)
        provider.push(by=by)
    forex_data = [
        ("EURUSD", "Forex (Major)", "EUR", "Euro", "USD", "US Dollar", "Euro vs US Dollar"),
        ("USDJPY", "Forex (Major)", "USD", "US Dollar", "JPY", "Japanese Yen", "US Dollar vs Japanese Yen"),
        ("GBPUSD", "Forex (Major)", "GBP", "British Pound", "USD", "US Dollar", "British Pound vs US Dollar"),
        ("USDCHF", "Forex (Major)", "USD", "US Dollar", "CHF", "Swiss Franc", "US Dollar vs Swiss Franc"),
        ("AUDUSD", "Forex (Major)", "AUD", "Australian Dollar", "USD", "US Dollar", "Australian Dollar vs US Dollar"),
        ("USDCAD", "Forex (Major)", "USD", "US Dollar", "CAD", "Canadian Dollar", "US Dollar vs Canadian Dollar"),
        ("NZDUSD", "Forex (Major)", "NZD", "New Zealand Dollar", "USD", "US Dollar", "New Zealand Dollar vs US Dollar"),
        ("EURGBP", "Forex (Minor)", "EUR", "Euro", "GBP", "British Pound", "Euro vs British Pound"),
        ("EURJPY", "Forex (Minor)", "EUR", "Euro", "JPY", "Japanese Yen", "Euro vs Japanese Yen"),
        ("EURCHF", "Forex (Minor)", "EUR", "Euro", "CHF", "Swiss Franc", "Euro vs Swiss Franc"),
        ("EURAUD", "Forex (Minor)", "EUR", "Euro", "AUD", "Australian Dollar", "Euro vs Australian Dollar"),
        ("EURCAD", "Forex (Minor)", "EUR", "Euro", "CAD", "Canadian Dollar", "Euro vs Canadian Dollar"),
        ("EURNZD", "Forex (Minor)", "EUR", "Euro", "NZD", "New Zealand Dollar", "Euro vs New Zealand Dollar"),
        ("GBPJPY", "Forex (Minor)", "GBP", "British Pound", "JPY", "Japanese Yen", "British Pound vs Japanese Yen"),
        ("GBPCHF", "Forex (Minor)", "GBP", "British Pound", "CHF", "Swiss Franc", "British Pound vs Swiss Franc"),
        ("GBPAUD", "Forex (Minor)", "GBP", "British Pound", "AUD", "Australian Dollar", "British Pound vs Australian Dollar"),
        ("GBPCAD", "Forex (Minor)", "GBP", "British Pound", "CAD", "Canadian Dollar", "British Pound vs Canadian Dollar"),
        ("GBPNZD", "Forex (Minor)", "GBP", "British Pound", "NZD", "New Zealand Dollar", "British Pound vs New Zealand Dollar"),
        ("CHFJPY", "Forex (Minor)", "CHF", "Swiss Franc", "JPY", "Japanese Yen", "Swiss Franc vs Japanese Yen"),
        ("AUDJPY", "Forex (Minor)", "AUD", "Australian Dollar", "JPY", "Japanese Yen", "Australian Dollar vs Japanese Yen"),
        ("AUDCHF", "Forex (Minor)", "AUD", "Australian Dollar", "CHF", "Swiss Franc", "Australian Dollar vs Swiss Franc"),
        ("AUDCAD", "Forex (Minor)", "AUD", "Australian Dollar", "CAD", "Canadian Dollar", "Australian Dollar vs Canadian Dollar"),
        ("AUDNZD", "Forex (Minor)", "AUD", "Australian Dollar", "NZD", "New Zealand Dollar", "Australian Dollar vs New Zealand Dollar"),
        ("CADJPY", "Forex (Minor)", "CAD", "Canadian Dollar", "JPY", "Japanese Yen", "Canadian Dollar vs Japanese Yen"),
        ("CADCHF", "Forex (Minor)", "CAD", "Canadian Dollar", "CHF", "Swiss Franc", "Canadian Dollar vs Swiss Franc"),
        ("NZDJPY", "Forex (Minor)", "NZD", "New Zealand Dollar", "JPY", "Japanese Yen", "New Zealand Dollar vs Japanese Yen"),
        ("NZDCHF", "Forex (Minor)", "NZD", "New Zealand Dollar", "CHF", "Swiss Franc", "New Zealand Dollar vs Swiss Franc"),
        ("NZDCAD", "Forex (Minor)", "NZD", "New Zealand Dollar", "CAD", "Canadian Dollar", "New Zealand Dollar vs Canadian Dollar"),
        ("USDHKD", "Forex (Exotic)", "USD", "US Dollar", "HKD", "Hong Kong Dollar", "US Dollar vs Hong Kong Dollar"),
        ("USDSGD", "Forex (Exotic)", "USD", "US Dollar", "SGD", "Singapore Dollar", "US Dollar vs Singapore Dollar"),
        ("USDTRY", "Forex (Exotic)", "USD", "US Dollar", "TRY", "Turkish Lira", "US Dollar vs Turkish Lira"),
        ("USDMXN", "Forex (Exotic)", "USD", "US Dollar", "MXN", "Mexican Peso", "US Dollar vs Mexican Peso"),
        ("USDZAR", "Forex (Exotic)", "USD", "US Dollar", "ZAR", "South African Rand", "US Dollar vs South African Rand"),
        ("USDSEK", "Forex (Exotic)", "USD", "US Dollar", "SEK", "Swedish Krona", "US Dollar vs Swedish Krona"),
        ("USDNOK", "Forex (Exotic)", "USD", "US Dollar", "NOK", "Norwegian Krone", "US Dollar vs Norwegian Krone"),
        ("USDDKK", "Forex (Exotic)", "USD", "US Dollar", "DKK", "Danish Krone", "US Dollar vs Danish Krone"),
        ("USDCNH", "Forex (Exotic)", "USD", "US Dollar", "CNH", "Offshore Chinese Yuan", "US Dollar vs Offshore Chinese Yuan"),
        ("USDTHB", "Forex (Exotic)", "USD", "US Dollar", "THB", "Thai Baht", "US Dollar vs Thai Baht"),
        ("USDRUB", "Forex (Exotic)", "USD", "US Dollar", "RUB", "Russian Ruble", "US Dollar vs Russian Ruble"),
        ("USDPLN", "Forex (Exotic)", "USD", "US Dollar", "PLN", "Polish Zloty", "US Dollar vs Polish Zloty"),
        ("USDHUF", "Forex (Exotic)", "USD", "US Dollar", "HUF", "Hungarian Forint", "US Dollar vs Hungarian Forint"),
        ("USDSAR", "Forex (Exotic)", "USD", "US Dollar", "SAR", "Saudi Riyal", "US Dollar vs Saudi Riyal"),
        ("USDILS", "Forex (Exotic)", "USD", "US Dollar", "ILS", "Israeli New Shekel", "US Dollar vs Israeli New Shekel"),
        ("EURTRY", "Forex (Exotic)", "EUR", "Euro", "TRY", "Turkish Lira", "Euro vs Turkish Lira"),
        ("EURSEK", "Forex (Exotic)", "EUR", "Euro", "SEK", "Swedish Krona", "Euro vs Swedish Krona"),
        ("EURNOK", "Forex (Exotic)", "EUR", "Euro", "NOK", "Norwegian Krone", "Euro vs Norwegian Krone"),
        ("EURZAR", "Forex (Exotic)", "EUR", "Euro", "ZAR", "South African Rand", "Euro vs South African Rand"),
        ("EURHUF", "Forex (Exotic)", "EUR", "Euro", "HUF", "Hungarian Forint", "Euro vs Hungarian Forint"),
        ("EURPLN", "Forex (Exotic)", "EUR", "Euro", "PLN", "Polish Zloty", "Euro vs Polish Zloty"),
        ("GBPMXN", "Forex (Exotic)", "GBP", "British Pound", "MXN", "Mexican Peso", "British Pound vs Mexican Peso"),
        ("SGDJPY", "Forex (Exotic)", "SGD", "Singapore Dollar", "JPY", "Japanese Yen", "Singapore Dollar vs Japanese Yen"),
        ("NOKJPY", "Forex (Exotic)", "NOK", "Norwegian Krone", "JPY", "Japanese Yen", "Norwegian Krone vs Japanese Yen"),
        ("SEKJPY", "Forex (Exotic)", "SEK", "Swedish Krona", "JPY", "Japanese Yen", "Swedish Krona vs Japanese Yen"),
        ("GBPZAR", "Forex (Exotic)", "GBP", "British Pound", "ZAR", "South African Rand", "British Pound vs South African Rand"),
        ("EURMXN", "Forex (Exotic)", "EUR", "Euro", "MXN", "Mexican Peso", "Euro vs Mexican Peso"),
        ("EURDKK", "Forex (Exotic)", "EUR", "Euro", "DKK", "Danish Krone", "Euro vs Danish Krone"),
        ("EURHKD", "Forex (Exotic)", "EUR", "Euro", "HKD", "Hong Kong Dollar", "Euro vs Hong Kong Dollar"),
        ("GBPNOK", "Forex (Exotic)", "GBP", "British Pound", "NOK", "Norwegian Krone", "British Pound vs Norwegian Krone"),
        ("EURCZK", "Forex (Exotic)", "EUR", "Euro", "CZK", "Czech Koruna", "Euro vs Czech Koruna"),
        ("NZDSGD", "Forex (Exotic)", "NZD", "New Zealand Dollar", "SGD", "Singapore Dollar", "New Zealand Dollar vs Singapore Dollar"),
        ("USDCZK", "Forex (Exotic)", "USD", "US Dollar", "CZK", "Czech Koruna", "US Dollar vs Czech Koruna"),
        ("GBPSGD", "Forex (Exotic)", "GBP", "British Pound", "SGD", "Singapore Dollar", "British Pound vs Singapore Dollar"),
        ("AUDSGD", "Forex (Exotic)", "AUD", "Australian Dollar", "SGD", "Singapore Dollar", "Australian Dollar vs Singapore Dollar"),
        ("AUDZAR", "Forex (Exotic)", "AUD", "Australian Dollar", "ZAR", "South African Rand", "Australian Dollar vs South African Rand"),
        ("CADMXN", "Forex (Exotic)", "CAD", "Canadian Dollar", "MXN", "Mexican Peso", "Canadian Dollar vs Mexican Peso"),
        ("CHFSGD", "Forex (Exotic)", "CHF", "Swiss Franc", "SGD", "Singapore Dollar", "Swiss Franc vs Singapore Dollar"),
        ("EURCNH", "Forex (Exotic)", "EUR", "Euro", "CNH", "Offshore Chinese Yuan", "Euro vs Offshore Chinese Yuan"),
        ("EURSGD", "Forex (Exotic)", "EUR", "Euro", "SGD", "Singapore Dollar", "Euro vs Singapore Dollar"),
        ("GBPDKK", "Forex (Exotic)", "GBP", "British Pound", "DKK", "Danish Krone", "British Pound vs Danish Krone"),
        ("GBPTRY", "Forex (Exotic)", "GBP", "British Pound", "TRY", "Turkish Lira", "British Pound vs Turkish Lira"),
        ("NOKSEK", "Forex (Exotic)", "NOK", "Norwegian Krone", "SEK", "Swedish Krona", "Norwegian Krone vs Swedish Krona"),
        ("NZDSEK", "Forex (Exotic)", "NZD", "New Zealand Dollar", "SEK", "Swedish Krona", "New Zealand Dollar vs Swedish Krona"),
        ("GBPSEK", "Forex (Exotic)", "GBP", "British Pound", "SEK", "Swedish Krona", "British Pound vs Swedish Krona"),
        ("AUDDKK", "Forex (Exotic)", "AUD", "Australian Dollar", "DKK", "Danish Krone", "Australian Dollar vs Danish Krone"),
        ("AUDHUF", "Forex (Exotic)", "AUD", "Australian Dollar", "HUF", "Hungarian Forint", "Australian Dollar vs Hungarian Forint"),
        ("AUDNOK", "Forex (Exotic)", "AUD", "Australian Dollar", "NOK", "Norwegian Krone", "Australian Dollar vs Norwegian Krone"),
        ("AUDPLN", "Forex (Exotic)", "AUD", "Australian Dollar", "PLN", "Polish Zloty", "Australian Dollar vs Polish Zloty"),
        ("CADSGD", "Forex (Exotic)", "CAD", "Canadian Dollar", "SGD", "Singapore Dollar", "Canadian Dollar vs Singapore Dollar"),
        ("CHFDKK", "Forex (Exotic)", "CHF", "Swiss Franc", "DKK", "Danish Krone", "Swiss Franc vs Danish Krone"),
        ("CHFHUF", "Forex (Exotic)", "CHF", "Swiss Franc", "HUF", "Hungarian Forint", "Swiss Franc vs Hungarian Forint"),
        ("CHFNOK", "Forex (Exotic)", "CHF", "Swiss Franc", "NOK", "Norwegian Krone", "Swiss Franc vs Norwegian Krone"),
        ("CHFPLN", "Forex (Exotic)", "CHF", "Swiss Franc", "PLN", "Polish Zloty", "Swiss Franc vs Polish Zloty"),
        ("CHFSEK", "Forex (Exotic)", "CHF", "Swiss Franc", "SEK", "Swedish Krona", "Swiss Franc vs Swedish Krona"),
        ("CNHJPY", "Forex (Exotic)", "CNH", "Offshore Chinese Yuan", "JPY", "Japanese Yen", "Offshore Chinese Yuan vs Japanese Yen"),
        ("EURILS", "Forex (Exotic)", "EUR", "Euro", "ILS", "Israeli New Shekel", "Euro vs Israeli New Shekel"),
        ("GBPCNH", "Forex (Exotic)", "GBP", "British Pound", "CNH", "Offshore Chinese Yuan", "British Pound vs Offshore Chinese Yuan"),
        ("GBPHUF", "Forex (Exotic)", "GBP", "British Pound", "HUF", "Hungarian Forint", "British Pound vs Hungarian Forint"),
        ("MXNJPY", "Forex (Exotic)", "MXN", "Mexican Peso", "JPY", "Japanese Yen", "Mexican Peso vs Japanese Yen"),
        ("NZDCNH", "Forex (Exotic)", "NZD", "New Zealand Dollar", "CNH", "Offshore Chinese Yuan", "New Zealand Dollar vs Offshore Chinese Yuan"),
        ("NZDHUF", "Forex (Exotic)", "NZD", "New Zealand Dollar", "HUF", "Hungarian Forint", "New Zealand Dollar vs Hungarian Forint"),
        ("USDBRL", "Forex (Exotic)", "USD", "US Dollar", "BRL", "Brazilian Real", "US Dollar vs Brazilian Real"),
        ("USDCLP", "Forex (Exotic)", "USD", "US Dollar", "CLP", "Chilean Peso", "US Dollar vs Chilean Peso"),
        ("USDCOP", "Forex (Exotic)", "USD", "US Dollar", "COP", "Colombian Peso", "US Dollar vs Colombian Peso"),
        ("USDIDR", "Forex (Exotic)", "USD", "US Dollar", "IDR", "Indonesian Rupiah", "US Dollar vs Indonesian Rupiah"),
        ("USDINR", "Forex (Exotic)", "USD", "US Dollar", "INR", "Indian Rupee", "US Dollar vs Indian Rupee"),
        ("USDKRW", "Forex (Exotic)", "USD", "US Dollar", "KRW", "South Korean Won", "US Dollar vs South Korean Won"),
        ("USDRON", "Forex (Exotic)", "USD", "US Dollar", "RON", "Romanian Leu", "US Dollar vs Romanian Leu"),
        ("USDTWD", "Forex (Exotic)", "USD", "US Dollar", "TWD", "New Taiwan Dollar", "US Dollar vs New Taiwan Dollar"),
        ("ZARJPY", "Forex (Exotic)", "ZAR", "South African Rand", "JPY", "Japanese Yen", "South African Rand vs Japanese Yen"),
    ]
    index_data = [
        ("US500", "Index (AMER) Equity", "US500", "S&P 500", "USD", "US Dollar", "S&P 500 vs US Dollar"),
        ("US30", "Index (AMER) Equity", "US30", "Dow Jones Industrial Average", "USD", "US Dollar", "Dow Jones Industrial Average vs US Dollar"),
        ("NAS100", "Index (AMER) Equity", "NAS100", "Nasdaq 100", "USD", "US Dollar", "Nasdaq 100 vs US Dollar"),
        ("US2000", "Index (AMER) Equity", "US2000", "Russell 2000", "USD", "US Dollar", "Russell 2000 vs US Dollar"),
        ("US400", "Index (AMER) Equity", "US400", "S&P MidCap 400", "USD", "US Dollar", "S&P MidCap 400 vs US Dollar"),
        ("CA60", "Index (AMER) Equity", "CA60", "S&P/TSX 60", "CAD", "Canadian Dollar", "S&P/TSX 60 vs Canadian Dollar"),
        ("VIX", "Index (AMER) Equity", "VIX", "CBOE Volatility Index", "USD", "US Dollar", "CBOE Volatility Index vs US Dollar"),
        ("BRA60", "Index (AMER) Equity", "BRA60", "Bovespa Index", "BRL", "Brazilian Real", "Bovespa Index vs Brazilian Real"),
        ("MEX35", "Index (AMER) Equity", "MEX35", "IPC Index", "MXN", "Mexican Peso", "IPC Index vs Mexican Peso"),
        ("GER40", "Index (EMEA) Equity", "GER40", "DAX 40", "EUR", "Euro", "DAX 40 vs Euro"),
        ("FRA40", "Index (EMEA) Equity", "FRA40", "CAC 40", "EUR", "Euro", "CAC 40 vs Euro"),
        ("UK100", "Index (EMEA) Equity", "UK100", "FTSE 100", "GBP", "British Pound", "FTSE 100 vs British Pound"),
        ("STOXX50", "Index (EMEA) Equity", "STOXX50", "EURO STOXX 50", "EUR", "Euro", "EURO STOXX 50 vs Euro"),
        ("IT40", "Index (EMEA) Equity", "IT40", "FTSE MIB", "EUR", "Euro", "FTSE MIB vs Euro"),
        ("SPA35", "Index (EMEA) Equity", "SPA35", "IBEX 35", "EUR", "Euro", "IBEX 35 vs Euro"),
        ("SWI20", "Index (EMEA) Equity", "SWI20", "Swiss Market Index", "CHF", "Swiss Franc", "Swiss Market Index vs Swiss Franc"),
        ("NETH25", "Index (EMEA) Equity", "NETH25", "AEX Index", "EUR", "Euro", "AEX Index vs Euro"),
        ("SE30", "Index (EMEA) Equity", "SE30", "OMX Stockholm 30", "SEK", "Swedish Krona", "OMX Stockholm 30 vs Swedish Krona"),
        ("NOR25", "Index (EMEA) Equity", "NOR25", "OBX Index", "NOK", "Norwegian Krone", "OBX Index vs Norwegian Krone"),
        ("SA40", "Index (EMEA) Equity", "SA40", "FTSE/JSE Top 40", "ZAR", "South African Rand", "FTSE/JSE Top 40 vs South African Rand"),
        ("TECDE30", "Index (EMEA) Equity", "TECDE30", "TecDAX", "EUR", "Euro", "TecDAX vs Euro"),
        ("MIDDE60", "Index (EMEA) Equity", "MIDDE60", "MDAX", "EUR", "Euro", "MDAX vs Euro"),
        ("PL20", "Index (EMEA) Equity", "PL20", "WIG20", "PLN", "Polish Zloty", "WIG20 vs Polish Zloty"),
        ("JP225", "Index (APAC) Equity", "JP225", "Nikkei 225", "JPY", "Japanese Yen", "Nikkei 225 vs Japanese Yen"),
        ("AUS200", "Index (APAC) Equity", "AUS200", "S&P/ASX 200", "AUD", "Australian Dollar", "S&P/ASX 200 vs Australian Dollar"),
        ("HK50", "Index (APAC) Equity", "HK50", "Hang Seng Index", "HKD", "Hong Kong Dollar", "Hang Seng Index vs Hong Kong Dollar"),
        ("CHINAH", "Index (APAC) Equity", "CHINAH", "Hang Seng China Enterprises Index", "HKD", "Hong Kong Dollar", "Hang Seng China Enterprises Index vs Hong Kong Dollar"),
        ("CN50", "Index (APAC) Equity", "CN50", "FTSE China A50", "USD", "US Dollar", "FTSE China A50 vs US Dollar"),
        ("HSTECH", "Index (APAC) Equity", "HSTECH", "Hang Seng Tech Index", "HKD", "Hong Kong Dollar", "Hang Seng Tech Index vs Hong Kong Dollar"),
        ("SCI25", "Index (APAC) Equity", "SCI25", "MSCI Singapore Index", "SGD", "Singapore Dollar", "MSCI Singapore Index vs Singapore Dollar"),
        ("TWN", "Index (APAC) Equity", "TWN", "MSCI Taiwan Index", "USD", "US Dollar", "MSCI Taiwan Index vs US Dollar"),
        ("INDIA50", "Index (APAC) Equity", "INDIA50", "Nifty 50", "USD", "US Dollar", "Nifty 50 vs US Dollar"),
        ("USDX", "Index (AMER) Currency", "USD", "US Dollar Index", "INDEX", "Index Points", "US Dollar Index vs Index Points"),
        ("EURX", "Index (EMEA) Currency", "EUR", "Euro Index", "INDEX", "Index Points", "Euro Index vs Index Points"),
        ("JPYX", "Index (APAC) Currency", "JPY", "Japanese Yen Index", "INDEX", "Index Points", "Japanese Yen Index vs Index Points"),
        ("GBPX", "Index (EMEA) Currency", "GBP", "British Pound Index", "INDEX", "Index Points", "British Pound Index vs Index Points"),
        ("AUDX", "Index (APAC) Currency", "AUD", "Australian Dollar Index", "INDEX", "Index Points", "Australian Dollar Index vs Index Points"),
        ("CADX", "Index (AMER) Currency", "CAD", "Canadian Dollar Index", "INDEX", "Index Points", "Canadian Dollar Index vs Index Points"),
        ("CHFX", "Index (EMEA) Currency", "CHF", "Swiss Franc Index", "INDEX", "Index Points", "Swiss Franc Index vs Index Points"),
        ("NZDX", "Index (APAC) Currency", "NZD", "New Zealand Dollar Index", "INDEX", "Index Points", "New Zealand Dollar Index vs Index Points"),
    ]
    crypto_data = [
        ("BTCUSD", "Crypto (Major)", "BTC", "Bitcoin", "USD", "US Dollar", "Bitcoin vs US Dollar"),
        ("BTCEUR", "Crypto (Major)", "BTC", "Bitcoin", "EUR", "Euro", "Bitcoin vs Euro"),
        ("BTCGBP", "Crypto (Major)", "BTC", "Bitcoin", "GBP", "British Pound", "Bitcoin vs British Pound"),
        ("BTCAUD", "Crypto (Major)", "BTC", "Bitcoin", "AUD", "Australian Dollar", "Bitcoin vs Australian Dollar"),
        ("ETHUSD", "Crypto (Major)", "ETH", "Ethereum", "USD", "US Dollar", "Ethereum vs US Dollar"),
        ("ETHEUR", "Crypto (Major)", "ETH", "Ethereum", "EUR", "Euro", "Ethereum vs Euro"),
        ("ETHGBP", "Crypto (Major)", "ETH", "Ethereum", "GBP", "British Pound", "Ethereum vs British Pound"),
        ("ETHAUD", "Crypto (Major)", "ETH", "Ethereum", "AUD", "Australian Dollar", "Ethereum vs Australian Dollar"),
        ("SOLUSD", "Crypto (Minor)", "SOL", "Solana", "USD", "US Dollar", "Solana vs US Dollar"),
        ("ADAUSD", "Crypto (Minor)", "ADA", "Cardano", "USD", "US Dollar", "Cardano vs US Dollar"),
        ("DOTUSD", "Crypto (Minor)", "DOT", "Polkadot", "USD", "US Dollar", "Polkadot vs US Dollar"),
        ("AVAXUSD", "Crypto (Minor)", "AVAX", "Avalanche", "USD", "US Dollar", "Avalanche vs US Dollar"),
        ("XRPUSD", "Crypto (Minor)", "XRP", "Ripple", "USD", "US Dollar", "Ripple vs US Dollar"),
        ("LINKUSD", "Crypto (Minor)", "LINK", "Chainlink", "USD", "US Dollar", "Chainlink vs US Dollar"),
        ("LTCUSD", "Crypto (Minor)", "LTC", "Litecoin", "USD", "US Dollar", "Litecoin vs US Dollar"),
        ("BCHUSD", "Crypto (Minor)", "BCH", "Bitcoin Cash", "USD", "US Dollar", "Bitcoin Cash vs US Dollar"),
        ("XLMUSD", "Crypto (Minor)", "XLM", "Stellar", "USD", "US Dollar", "Stellar vs US Dollar"),
        ("UNIUSD", "Crypto (Minor)", "UNI", "Uniswap", "USD", "US Dollar", "Uniswap vs US Dollar"),
        ("BNBUSD", "Crypto (Minor)", "BNB", "Binance Coin", "USD", "US Dollar", "Binance Coin vs US Dollar"),
        ("TRXUSD", "Crypto (Minor)", "TRX", "Tron", "USD", "US Dollar", "Tron vs US Dollar"),
        ("TONUSD", "Crypto (Minor)", "TON", "Toncoin", "USD", "US Dollar", "Toncoin vs US Dollar"),
        ("MATICUSD", "Crypto (Minor)", "POL", "Polygon", "USD", "US Dollar", "Polygon vs US Dollar"),
        ("APTUSD", "Crypto (Minor)", "APT", "Aptos", "USD", "US Dollar", "Aptos vs US Dollar"),
        ("SUIUSD", "Crypto (Minor)", "SUI", "Sui", "USD", "US Dollar", "Sui vs US Dollar"),
        ("NEARUSD", "Crypto (Minor)", "NEAR", "NEAR Protocol", "USD", "US Dollar", "NEAR Protocol vs US Dollar"),
        ("RENDERUSD", "Crypto (Minor)", "RENDER", "Render Token", "USD", "US Dollar", "Render Token vs US Dollar"),
        ("FETUSD", "Crypto (Minor)", "FET", "Artificial Superintelligence Alliance", "USD", "US Dollar", "FET vs US Dollar"),
        ("HBARUSD", "Crypto (Minor)", "HBAR", "Hedera", "USD", "US Dollar", "Hedera vs US Dollar"),
        ("INJUSD", "Crypto (Minor)", "INJ", "Injective", "USD", "US Dollar", "Injective vs US Dollar"),
        ("AAVEUSD", "Crypto (Minor)", "AAVE", "Aave", "USD", "US Dollar", "Aave vs US Dollar"),
        ("JUPUSD", "Crypto (Minor)", "JUP", "Jupiter", "USD", "US Dollar", "Jupiter vs US Dollar"),
        ("ONDOUSD", "Crypto (Minor)", "ONDO", "Ondo", "USD", "US Dollar", "Ondo vs US Dollar"),
        ("DOGEUSD", "Crypto (Exotic)", "DOGE", "Dogecoin", "USD", "US Dollar", "Dogecoin vs US Dollar"),
        ("SHBUSD", "Crypto (Exotic)", "SHIB", "Shiba Inu", "USD", "US Dollar", "Shiba Inu vs US Dollar"),
        ("PEPUSD", "Crypto (Exotic)", "PEPE", "Pepe", "USD", "US Dollar", "Pepe vs US Dollar"),
        ("WIFUSD", "Crypto (Exotic)", "WIF", "dogwifhat", "USD", "US Dollar", "dogwifhat vs US Dollar"),
        ("BONKUSD", "Crypto (Exotic)", "BONK", "Bonk", "USD", "US Dollar", "Bonk vs US Dollar"),
        ("FLOKIUSD", "Crypto (Exotic)", "FLOKI", "Floki", "USD", "US Dollar", "Floki vs US Dollar"),
        ("TRUMPUSD", "Crypto (Exotic)", "TRUMP", "MAGA TRUMP", "USD", "US Dollar", "MAGA TRUMP vs US Dollar"),
        ("PAXGUSD", "Crypto (Exotic)", "PAXG", "Pax Gold", "USD", "US Dollar", "Pax Gold vs US Dollar"),
        ("XAUTUSD", "Crypto (Exotic)", "XAUT", "Tether Gold", "USD", "US Dollar", "Tether Gold vs US Dollar")
    ]
    metal_data = [
        ("XAUUSD", "Metal (Major)", "XAU", "Gold", "USD", "US Dollar", "Gold vs US Dollar"),
        ("XAUEUR", "Metal (Major)", "XAU", "Gold", "EUR", "Euro", "Gold vs Euro"),
        ("XAGUSD", "Metal (Major)", "XAG", "Silver", "USD", "US Dollar", "Silver vs US Dollar"),
        ("XAGEUR", "Metal (Major)", "XAG", "Silver", "EUR", "Euro", "Silver vs Euro"),
        ("XPTUSD", "Metal (Major)", "XPT", "Platinum", "USD", "US Dollar", "Platinum vs US Dollar"),
        ("XPDUSD", "Metal (Major)", "XPD", "Palladium", "USD", "US Dollar", "Palladium vs US Dollar"),
        ("XAUAUD", "Metal (Minor)", "XAU", "Gold", "AUD", "Australian Dollar", "Gold vs Australian Dollar"),
        ("XAUCHF", "Metal (Minor)", "XAU", "Gold", "CHF", "Swiss Franc", "Gold vs Swiss Franc"),
        ("XAUGBP", "Metal (Minor)", "XAU", "Gold", "GBP", "British Pound", "Gold vs British Pound"),
        ("XAUJPY", "Metal (Minor)", "XAU", "Gold", "JPY", "Japanese Yen", "Gold vs Japanese Yen"),
        ("XAUSGD", "Metal (Minor)", "XAU", "Gold", "SGD", "Singapore Dollar", "Gold vs Singapore Dollar"),
        ("XAUCNH", "Metal (Minor)", "XAU", "Gold", "CNH", "Offshore Chinese Yuan", "Gold vs Offshore Chinese Yuan"),
        ("XAUTHB", "Metal (Minor)", "XAU", "Gold", "THB", "Thai Baht", "Gold vs Thai Baht"),
        ("XAGAUD", "Metal (Minor)", "XAG", "Silver", "AUD", "Australian Dollar", "Silver vs Australian Dollar"),
        ("XAGSGD", "Metal (Minor)", "XAG", "Silver", "SGD", "Singapore Dollar", "Silver vs Singapore Dollar")
    ]
    energy_data = [
        ("XBRUSD", "Energy (Major)", "XBR", "Brent Crude Oil", "USD", "US Dollar", "Brent Crude Oil vs US Dollar"),
        ("XTIUSD", "Energy (Major)", "XTI", "WTI Crude Oil", "USD", "US Dollar", "WTI Crude Oil vs US Dollar"),
        ("XNGUSD", "Energy (Major)", "XNG", "Natural Gas", "USD", "US Dollar", "Natural Gas vs US Dollar"),
        ("XRBUSD", "Energy (Minor)", "XRB", "RBOB Gasoline", "USD", "US Dollar", "RBOB Gasoline vs US Dollar"),
        ("XHOUSD", "Energy (Minor)", "XHO", "Heating Oil", "USD", "US Dollar", "Heating Oil vs US Dollar")
    ]
    stock_data = [
        ("A.US", "Stock (US)", "A", "Agilent Technologies Inc", "USD", "US Dollar", "Agilent Technologies Inc vs US Dollar"),
        ("AA.US", "Stock (US)", "AA", "Alcoa Corp", "USD", "US Dollar", "Alcoa Corp vs US Dollar"),
        ("AAL.US", "Stock (US)", "AAL", "American Airlines Group Inc", "USD", "US Dollar", "American Airlines Group Inc vs US Dollar"),
        ("AAP.US", "Stock (US)", "AAP", "Advance Auto Parts Inc", "USD", "US Dollar", "Advance Auto Parts Inc vs US Dollar"),
        ("AAPL.US", "Stock (US)", "AAPL", "Apple Inc", "USD", "US Dollar", "Apple Inc vs US Dollar"),
        ("ABBV.US", "Stock (US)", "ABBV", "AbbVie Inc", "USD", "US Dollar", "AbbVie Inc vs US Dollar"),
        ("ABNB.US", "Stock (US)", "ABNB", "Airbnb Inc", "USD", "US Dollar", "Airbnb Inc vs US Dollar"),
        ("ABT.US", "Stock (US)", "ABT", "Abbott Laboratories", "USD", "US Dollar", "Abbott Laboratories vs US Dollar"),
        ("ACN.US", "Stock (US)", "ACN", "Accenture plc", "USD", "US Dollar", "Accenture plc vs US Dollar"),
        ("ADBE.US", "Stock (US)", "ADBE", "Adobe Inc", "USD", "US Dollar", "Adobe Inc vs US Dollar"),
        ("ADI.US", "Stock (US)", "ADI", "Analog Devices Inc", "USD", "US Dollar", "Analog Devices Inc vs US Dollar"),
        ("ADM.US", "Stock (US)", "ADM", "Archer-Daniels-Midland Co", "USD", "US Dollar", "Archer-Daniels-Midland Co vs US Dollar"),
        ("ADP.US", "Stock (US)", "ADP", "Automatic Data Processing Inc", "USD", "US Dollar", "Automatic Data Processing Inc vs US Dollar"),
        ("ADSK.US", "Stock (US)", "ADSK", "Autodesk Inc", "USD", "US Dollar", "Autodesk Inc vs US Dollar"),
        ("AEE.US", "Stock (US)", "AEE", "Ameren Corp", "USD", "US Dollar", "Ameren Corp vs US Dollar"),
        ("AEP.US", "Stock (US)", "AEP", "American Electric Power Co", "USD", "US Dollar", "American Electric Power Co vs US Dollar"),
        ("AES.US", "Stock (US)", "AES", "AES Corp", "USD", "US Dollar", "AES Corp vs US Dollar"),
        ("AFL.US", "Stock (US)", "AFL", "Aflac Inc", "USD", "US Dollar", "Aflac Inc vs US Dollar"),
        ("AIG.US", "Stock (US)", "AIG", "American International Group Inc", "USD", "US Dollar", "American International Group Inc vs US Dollar"),
        ("AIZ.US", "Stock (US)", "AIZ", "Assurant Inc", "USD", "US Dollar", "Assurant Inc vs US Dollar"),
        ("AJG.US", "Stock (US)", "AJG", "Arthur J. Gallagher & Co", "USD", "US Dollar", "Arthur J. Gallagher & Co vs US Dollar"),
        ("AKAM.US", "Stock (US)", "AKAM", "Akamai Technologies Inc", "USD", "US Dollar", "Akamai Technologies Inc vs US Dollar"),
        ("ALB.US", "Stock (US)", "ALB", "Albemarle Corp", "USD", "US Dollar", "Albemarle Corp vs US Dollar"),
        ("ALGN.US", "Stock (US)", "ALGN", "Align Technology Inc", "USD", "US Dollar", "Align Technology Inc vs US Dollar"),
        ("ALK.US", "Stock (US)", "ALK", "Alaska Air Group Inc", "USD", "US Dollar", "Alaska Air Group Inc vs US Dollar"),
        ("ALL.US", "Stock (US)", "ALL", "Allstate Corp", "USD", "US Dollar", "Allstate Corp vs US Dollar"),
        ("ALLE.US", "Stock (US)", "ALLE", "Allegion plc", "USD", "US Dollar", "Allegion plc vs US Dollar"),
        ("AMAT.US", "Stock (US)", "AMAT", "Applied Materials Inc", "USD", "US Dollar", "Applied Materials Inc vs US Dollar"),
        ("AMC.US", "Stock (US)", "AMC", "AMC Entertainment Holdings Inc", "USD", "US Dollar", "AMC Entertainment Holdings Inc vs US Dollar"),
        ("AMCR.US", "Stock (US)", "AMCR", "Amcor plc", "USD", "US Dollar", "Amcor plc vs US Dollar"),
        ("AMD.US", "Stock (US)", "AMD", "Advanced Micro Devices Inc", "USD", "US Dollar", "Advanced Micro Devices Inc vs US Dollar"),
        ("AME.US", "Stock (US)", "AME", "AMETEK Inc", "USD", "US Dollar", "AMETEK Inc vs US Dollar"),
        ("AMGN.US", "Stock (US)", "AMGN", "Amgen Inc", "USD", "US Dollar", "Amgen Inc vs US Dollar"),
        ("AMP.US", "Stock (US)", "AMP", "Ameriprise Financial Inc", "USD", "US Dollar", "Ameriprise Financial Inc vs US Dollar"),
        ("AMT.US", "Stock (US)", "AMT", "American Tower Corp", "USD", "US Dollar", "American Tower Corp vs US Dollar"),
        ("AMZN.US", "Stock (US)", "AMZN", "Amazon.com Inc", "USD", "US Dollar", "Amazon.com Inc vs US Dollar"),
        ("ANET.US", "Stock (US)", "ANET", "Arista Networks Inc", "USD", "US Dollar", "Arista Networks Inc vs US Dollar"),
        ("AON.US", "Stock (US)", "AON", "Aon plc", "USD", "US Dollar", "Aon plc vs US Dollar"),
        ("AOS.US", "Stock (US)", "AOS", "A.O. Smith Corp", "USD", "US Dollar", "A.O. Smith Corp vs US Dollar"),
        ("APA.US", "Stock (US)", "APA", "APA Corp", "USD", "US Dollar", "APA Corp vs US Dollar"),
        ("APD.US", "Stock (US)", "APD", "Air Products and Chemicals Inc", "USD", "US Dollar", "Air Products and Chemicals Inc vs US Dollar"),
        ("APH.US", "Stock (US)", "APH", "Amphenol Corp", "USD", "US Dollar", "Amphenol Corp vs US Dollar"),
        ("APTV.US", "Stock (US)", "APTV", "Aptiv plc", "USD", "US Dollar", "Aptiv plc vs US Dollar"),
        ("ARE.US", "Stock (US)", "ARE", "Alexandria Real Estate Equities Inc", "USD", "US Dollar", "Alexandria Real Estate Equities Inc vs US Dollar"),
        ("ASML.US", "Stock (US)", "ASML", "ASML Holding NV", "USD", "US Dollar", "ASML Holding NV vs US Dollar"),
        ("ATO.US", "Stock (US)", "ATO", "Atmos Energy Corp", "USD", "US Dollar", "Atmos Energy Corp vs US Dollar"),
        ("AUPH.US", "Stock (US)", "AUPH", "Aurinia Pharmaceuticals Inc", "USD", "US Dollar", "Aurinia Pharmaceuticals Inc vs US Dollar"),
        ("AVB.US", "Stock (US)", "AVB", "AvalonBay Communities Inc", "USD", "US Dollar", "AvalonBay Communities Inc vs US Dollar"),
        ("AVGO.US", "Stock (US)", "AVGO", "Broadcom Inc", "USD", "US Dollar", "Broadcom Inc vs US Dollar"),
        ("AVY.US", "Stock (US)", "AVY", "Avery Dennison Corp", "USD", "US Dollar", "Avery Dennison Corp vs US Dollar"),
        ("AWK.US", "Stock (US)", "AWK", "American Water Works Company Inc", "USD", "US Dollar", "American Water Works Company Inc vs US Dollar"),
        ("AXP.US", "Stock (US)", "AXP", "American Express Co", "USD", "US Dollar", "American Express Co vs US Dollar"),
        ("AZO.US", "Stock (US)", "AZO", "AutoZone Inc", "USD", "US Dollar", "AutoZone Inc vs US Dollar"),
        ("BA.US", "Stock (US)", "BA", "Boeing Co", "USD", "US Dollar", "Boeing Co vs US Dollar"),
        ("BABA.US", "Stock (US)", "BABA", "Alibaba Group Holding Ltd", "USD", "US Dollar", "Alibaba Group Holding Ltd vs US Dollar"),
        ("BAC.US", "Stock (US)", "BAC", "Bank of America Corp", "USD", "US Dollar", "Bank of America Corp vs US Dollar"),
        ("BALL.US", "Stock (US)", "BALL", "Ball Corp", "USD", "US Dollar", "Ball Corp vs US Dollar"),
        ("BAX.US", "Stock (US)", "BAX", "Baxter International Inc", "USD", "US Dollar", "Baxter International Inc vs US Dollar"),
        ("BBY.US", "Stock (US)", "BBY", "Best Buy Co Inc", "USD", "US Dollar", "Best Buy Co Inc vs US Dollar"),
        ("BDX.US", "Stock (US)", "BDX", "Becton Dickinson and Co", "USD", "US Dollar", "Becton Dickinson and Co vs US Dollar"),
        ("BEN.US", "Stock (US)", "BEN", "Franklin Resources Inc", "USD", "US Dollar", "Franklin Resources Inc vs US Dollar"),
        ("BF-B.US", "Stock (US)", "BF-B", "Brown-Forman Corp Class B", "USD", "US Dollar", "Brown-Forman Corp vs US Dollar"),
        ("BIDU.US", "Stock (US)", "BIDU", "Baidu Inc", "USD", "US Dollar", "Baidu Inc vs US Dollar"),
        ("BIIB.US", "Stock (US)", "BIIB", "Biogen Inc", "USD", "US Dollar", "Biogen Inc vs US Dollar"),
        ("BIO.US", "Stock (US)", "BIO", "Bio-Rad Laboratories Inc", "USD", "US Dollar", "Bio-Rad Laboratories Inc vs US Dollar"),
        ("BKNG.US", "Stock (US)", "BKNG", "Booking Holdings Inc", "USD", "US Dollar", "Booking Holdings Inc vs US Dollar"),
        ("BKR.US", "Stock (US)", "BKR", "Baker Hughes Co", "USD", "US Dollar", "Baker Hughes Co vs US Dollar"),
        ("BLK.US", "Stock (US)", "BLK", "BlackRock Inc", "USD", "US Dollar", "BlackRock Inc vs US Dollar"),
        ("BMBL.US", "Stock (US)", "BMBL", "Bumble Inc", "USD", "US Dollar", "Bumble Inc vs US Dollar"),
        ("BMY.US", "Stock (US)", "BMY", "Bristol-Myers Squibb Co", "USD", "US Dollar", "Bristol-Myers Squibb Co vs US Dollar"),
        ("BNTX.US", "Stock (US)", "BNTX", "BioNTech SE", "USD", "US Dollar", "BioNTech SE vs US Dollar"),
        ("BR.US", "Stock (US)", "BR", "Broadridge Financial Solutions Inc", "USD", "US Dollar", "Broadridge Financial Solutions Inc vs US Dollar"),
        ("BRK.B.US", "Stock (US)", "BRK.B", "Berkshire Hathaway Inc Class B", "USD", "US Dollar", "Berkshire Hathaway Inc vs US Dollar"),
        ("BSX.US", "Stock (US)", "BSX", "Boston Scientific Corp", "USD", "US Dollar", "Boston Scientific Corp vs US Dollar"),
        ("BWA.US", "Stock (US)", "BWA", "BorgWarner Inc", "USD", "US Dollar", "BorgWarner Inc vs US Dollar"),
        ("BXP.US", "Stock (US)", "BXP", "Boston Properties Inc", "USD", "US Dollar", "Boston Properties Inc vs US Dollar"),
        ("BYND.US", "Stock (US)", "BYND", "Beyond Meat Inc", "USD", "US Dollar", "Beyond Meat Inc vs US Dollar"),
        ("C.US", "Stock (US)", "C", "Citigroup Inc", "USD", "US Dollar", "Citigroup Inc vs US Dollar"),
        ("CAG.US", "Stock (US)", "CAG", "Conagra Brands Inc", "USD", "US Dollar", "Conagra Brands Inc vs US Dollar"),
        ("CAH.US", "Stock (US)", "CAH", "Cardinal Health Inc", "USD", "US Dollar", "Cardinal Health Inc vs US Dollar"),
        ("CAR.US", "Stock (US)", "CAR", "Avis Budget Group Inc", "USD", "US Dollar", "Avis Budget Group Inc vs US Dollar"),
        ("CARR.US", "Stock (US)", "CARR", "Carrier Global Corp", "USD", "US Dollar", "Carrier Global Corp vs US Dollar"),
        ("CAT.US", "Stock (US)", "CAT", "Caterpillar Inc", "USD", "US Dollar", "Caterpillar Inc vs US Dollar"),
        ("CB.US", "Stock (US)", "CB", "Chubb Limited", "USD", "US Dollar", "Chubb Limited vs US Dollar"),
        ("CBRE.US", "Stock (US)", "CBRE", "CBRE Group Inc", "USD", "US Dollar", "CBRE Group Inc vs US Dollar"),
        ("CCI.US", "Stock (US)", "CCI", "Crown Castle Inc", "USD", "US Dollar", "Crown Castle Inc vs US Dollar"),
        ("CCL.US", "Stock (US)", "CCL", "Carnival Corp", "USD", "US Dollar", "Carnival Corp vs US Dollar"),
        ("CDNS.US", "Stock (US)", "CDNS", "Cadence Design Systems Inc", "USD", "US Dollar", "Cadence Design Systems Inc vs US Dollar"),
        ("CDW.US", "Stock (US)", "CDW", "CDW Corp", "USD", "US Dollar", "CDW Corp vs US Dollar"),
        ("CE.US", "Stock (US)", "CE", "Celanese Corp", "USD", "US Dollar", "Celanese Corp vs US Dollar"),
        ("CF.US", "Stock (US)", "CF", "CF Industries Holdings Inc", "USD", "US Dollar", "CF Industries Holdings Inc vs US Dollar"),
        ("CFG.US", "Stock (US)", "CFG", "Citizens Financial Group Inc", "USD", "US Dollar", "Citizens Financial Group Inc vs US Dollar"),
        ("CGC.US", "Stock (US)", "CGC", "Canopy Growth Corp", "USD", "US Dollar", "Canopy Growth Corp vs US Dollar"),
        ("CHD.US", "Stock (US)", "CHD", "Church & Dwight Co Inc", "USD", "US Dollar", "Church & Dwight Co Inc vs US Dollar"),
        ("CHRW.US", "Stock (US)", "CHRW", "C.H. Robinson Worldwide Inc", "USD", "US Dollar", "C.H. Robinson Worldwide Inc vs US Dollar"),
        ("CHTR.US", "Stock (US)", "CHTR", "Charter Communications Inc", "USD", "US Dollar", "Charter Communications Inc vs US Dollar"),
        ("CI.US", "Stock (US)", "CI", "Cigna Group", "USD", "US Dollar", "Cigna Group vs US Dollar"),
        ("CINF.US", "Stock (US)", "CINF", "Cincinnati Financial Corp", "USD", "US Dollar", "Cincinnati Financial Corp vs US Dollar"),
        ("CL.US", "Stock (US)", "CL", "Colgate-Palmolive Co", "USD", "US Dollar", "Colgate-Palmolive Co vs US Dollar"),
        ("CME.US", "Stock (US)", "CME", "CME Group Inc", "USD", "US Dollar", "CME Group Inc vs US Dollar"),
        ("CMG.US", "Stock (US)", "CMG", "Chipotle Mexican Grill Inc", "USD", "US Dollar", "Chipotle Mexican Grill Inc vs US Dollar"),
        ("CMI.US", "Stock (US)", "CMI", "Cummins Inc", "USD", "US Dollar", "Cummins Inc vs US Dollar"),
        ("CMS.US", "Stock (US)", "CMS", "CMS Energy Corp", "USD", "US Dollar", "CMS Energy Corp vs US Dollar"),
        ("CNC.US", "Stock (US)", "CNC", "Centene Corp", "USD", "US Dollar", "Centene Corp vs US Dollar"),
        ("CNP.US", "Stock (US)", "CNP", "CenterPoint Energy Inc", "USD", "US Dollar", "CenterPoint Energy Inc vs US Dollar"),
        ("COF.US", "Stock (US)", "COF", "Capital One Financial Corp", "USD", "US Dollar", "Capital One Financial Corp vs US Dollar"),
        ("COIN.US", "Stock (US)", "COIN", "Coinbase Global Inc", "USD", "US Dollar", "Coinbase Global Inc vs US Dollar"),
        ("COP.US", "Stock (US)", "COP", "ConocoPhillips", "USD", "US Dollar", "ConocoPhillips vs US Dollar"),
        ("COST.US", "Stock (US)", "COST", "Costco Wholesale Corp", "USD", "US Dollar", "Costco Wholesale Corp vs US Dollar"),
        ("CPB.US", "Stock (US)", "CPB", "Campbell Soup Co", "USD", "US Dollar", "Campbell Soup Co vs US Dollar"),
        ("CPRT.US", "Stock (US)", "CPRT", "Copart Inc", "USD", "US Dollar", "Copart Inc vs US Dollar"),
        ("CRM.US", "Stock (US)", "CRM", "Salesforce Inc", "USD", "US Dollar", "Salesforce Inc vs US Dollar"),
        ("CRON.US", "Stock (US)", "CRON", "Cronos Group Inc", "USD", "US Dollar", "Cronos Group Inc vs US Dollar"),
        ("CSCO.US", "Stock (US)", "CSCO", "Cisco Systems Inc", "USD", "US Dollar", "Cisco Systems Inc vs US Dollar"),
        ("CSX.US", "Stock (US)", "CSX", "CSX Corp", "USD", "US Dollar", "CSX Corp vs US Dollar"),
        ("CTAS.US", "Stock (US)", "CTAS", "Cintas Corp", "USD", "US Dollar", "Cintas Corp vs US Dollar"),
        ("CTSH.US", "Stock (US)", "CTSH", "Cognizant Technology Solutions Corp", "USD", "US Dollar", "Cognizant Technology Solutions Corp vs US Dollar"),
        ("CTVA.US", "Stock (US)", "CTVA", "Corteva Inc", "USD", "US Dollar", "Corteva Inc vs US Dollar"),
        ("CVS.US", "Stock (US)", "CVS", "CVS Health Corp", "USD", "US Dollar", "CVS Health Corp vs US Dollar"),
        ("CVX.US", "Stock (US)", "CVX", "Chevron Corp", "USD", "US Dollar", "Chevron Corp vs US Dollar"),
        ("D.US", "Stock (US)", "D", "Dominion Energy Inc", "USD", "US Dollar", "Dominion Energy Inc vs US Dollar"),
        ("DAL.US", "Stock (US)", "DAL", "Delta Air Lines Inc", "USD", "US Dollar", "Delta Air Lines Inc vs US Dollar"),
        ("DBX.US", "Stock (US)", "DBX", "Dropbox Inc", "USD", "US Dollar", "Dropbox Inc vs US Dollar"),
        ("DE.US", "Stock (US)", "DE", "Deere & Co", "USD", "US Dollar", "Deere & Co vs US Dollar"),
        ("DEO.US", "Stock (US)", "DEO", "Diageo plc", "USD", "US Dollar", "Diageo plc vs US Dollar"),
        ("DG.US", "Stock (US)", "DG", "Dollar General Corp", "USD", "US Dollar", "Dollar General Corp vs US Dollar"),
        ("DHI.US", "Stock (US)", "DHI", "D.R. Horton Inc", "USD", "US Dollar", "D.R. Horton Inc vs US Dollar"),
        ("DHR.US", "Stock (US)", "DHR", "Danaher Corp", "USD", "US Dollar", "Danaher Corp vs US Dollar"),
        ("DIS.US", "Stock (US)", "DIS", "Walt Disney Co", "USD", "US Dollar", "Walt Disney Co vs US Dollar"),
        ("DLR.US", "Stock (US)", "DLR", "Digital Realty Trust Inc", "USD", "US Dollar", "Digital Realty Trust Inc vs US Dollar"),
        ("DLTR.US", "Stock (US)", "DLTR", "Dollar Tree Inc", "USD", "US Dollar", "Dollar Tree Inc vs US Dollar"),
        ("DOW.US", "Stock (US)", "DOW", "Dow Inc", "USD", "US Dollar", "Dow Inc vs US Dollar"),
        ("DOV.US", "Stock (US)", "DOV", "Dover Corp", "USD", "US Dollar", "Dover Corp vs US Dollar"),
        ("DPZ.US", "Stock (US)", "DPZ", "Domino's Pizza Inc", "USD", "US Dollar", "Domino's Pizza Inc vs US Dollar"),
        ("DRI.US", "Stock (US)", "DRI", "Darden Restaurants Inc", "USD", "US Dollar", "Darden Restaurants Inc vs US Dollar"),
        ("DTE.US", "Stock (US)", "DTE", "DTE Energy Co", "USD", "US Dollar", "DTE Energy Co vs US Dollar"),
        ("DUK.US", "Stock (US)", "DUK", "Duke Energy Corp", "USD", "US Dollar", "Duke Energy Corp vs US Dollar"),
        ("DVA.US", "Stock (US)", "DVA", "DaVita Inc", "USD", "US Dollar", "DaVita Inc vs US Dollar"),
        ("DVN.US", "Stock (US)", "DVN", "Devon Energy Corp", "USD", "US Dollar", "Devon Energy Corp vs US Dollar"),
        ("DXC.US", "Stock (US)", "DXC", "DXC Technology Co", "USD", "US Dollar", "DXC Technology Co vs US Dollar"),
        ("DXCM.US", "Stock (US)", "DXCM", "DexCom Inc", "USD", "US Dollar", "DexCom Inc vs US Dollar"),
        ("EA.US", "Stock (US)", "EA", "Electronic Arts Inc", "USD", "US Dollar", "Electronic Arts Inc vs US Dollar"),
        ("EBAY.US", "Stock (US)", "EBAY", "eBay Inc", "USD", "US Dollar", "eBay Inc vs US Dollar"),
        ("ECL.US", "Stock (US)", "ECL", "Ecolab Inc", "USD", "US Dollar", "Ecolab Inc vs US Dollar"),
        ("ED.US", "Stock (US)", "ED", "Consolidated Edison Inc", "USD", "US Dollar", "Consolidated Edison Inc vs US Dollar"),
        ("EFX.US", "Stock (US)", "EFX", "Equifax Inc", "USD", "US Dollar", "Equifax Inc vs US Dollar"),
        ("EIX.US", "Stock (US)", "EIX", "Edison International", "USD", "US Dollar", "Edison International vs US Dollar"),
        ("EL.US", "Stock (US)", "EL", "Estée Lauder Companies Inc", "USD", "US Dollar", "Estée Lauder Companies Inc vs US Dollar"),
        ("EMN.US", "Stock (US)", "EMN", "Eastman Chemical Co", "USD", "US Dollar", "Eastman Chemical Co vs US Dollar"),
        ("EMR.US", "Stock (US)", "EMR", "Emerson Electric Co", "USD", "US Dollar", "Emerson Electric Co vs US Dollar"),
        ("ENPH.US", "Stock (US)", "ENPH", "Enphase Energy Inc", "USD", "US Dollar", "Enphase Energy Inc vs US Dollar"),
        ("EOG.US", "Stock (US)", "EOG", "EOG Resources Inc", "USD", "US Dollar", "EOG Resources Inc vs US Dollar"),
        ("EQIX.US", "Stock (US)", "EQIX", "Equinix Inc", "USD", "US Dollar", "Equinix Inc vs US Dollar"),
        ("EQR.US", "Stock (US)", "EQR", "Equity Residential", "USD", "US Dollar", "Equity Residential vs US Dollar"),
        ("ES.US", "Stock (US)", "ES", "Eversource Energy", "USD", "US Dollar", "Eversource Energy vs US Dollar"),
        ("ESS.US", "Stock (US)", "ESS", "Essex Property Trust Inc", "USD", "US Dollar", "Essex Property Trust Inc vs US Dollar"),
        ("ETN.US", "Stock (US)", "ETN", "Eaton Corp plc", "USD", "US Dollar", "Eaton Corp plc vs US Dollar"),
        ("ETR.US", "Stock (US)", "ETR", "Entergy Corp", "USD", "US Dollar", "Entergy Corp vs US Dollar"),
        ("ETSY.US", "Stock (US)", "ETSY", "Etsy Inc", "USD", "US Dollar", "Etsy Inc vs US Dollar"),
        ("EVRG.US", "Stock (US)", "EVRG", "Evergy Inc", "USD", "US Dollar", "Evergy Inc vs US Dollar"),
        ("EW.US", "Stock (US)", "EW", "Edwards Lifesciences Corp", "USD", "US Dollar", "Edwards Lifesciences Corp vs US Dollar"),
        ("EXC.US", "Stock (US)", "EXC", "Exelon Corp", "USD", "US Dollar", "Exelon Corp vs US Dollar"),
        ("EXPD.US", "Stock (US)", "EXPD", "Expeditors International of Washington Inc", "USD", "US Dollar", "Expeditors International vs US Dollar"),
        ("EXPE.US", "Stock (US)", "EXPE", "Expedia Group Inc", "USD", "US Dollar", "Expedia Group Inc vs US Dollar"),
        ("EXR.US", "Stock (US)", "EXR", "Extra Space Storage Inc", "USD", "US Dollar", "Extra Space Storage Inc vs US Dollar"),
        ("F.US", "Stock (US)", "F", "Ford Motor Co", "USD", "US Dollar", "Ford Motor Co vs US Dollar"),
        ("FANG.US", "Stock (US)", "FANG", "Diamondback Energy Inc", "USD", "US Dollar", "Diamondback Energy Inc vs US Dollar"),
        ("FAST.US", "Stock (US)", "FAST", "Fastenal Co", "USD", "US Dollar", "Fastenal Co vs US Dollar"),
        ("FCX.US", "Stock (US)", "FCX", "Freeport-McMoRan Inc", "USD", "US Dollar", "Freeport-McMoRan Inc vs US Dollar"),
        ("FDX.US", "Stock (US)", "FDX", "FedEx Corp", "USD", "US Dollar", "FedEx Corp vs US Dollar"),
        ("FE.US", "Stock (US)", "FE", "FirstEnergy Corp", "USD", "US Dollar", "FirstEnergy Corp vs US Dollar"),
        ("FET.US", "Stock (US)", "FET", "Artificial Superintelligence Alliance", "USD", "US Dollar", "FET vs US Dollar"),
        ("FFIV.US", "Stock (US)", "FFIV", "F5 Inc", "USD", "US Dollar", "F5 Inc vs US Dollar"),
        ("FIS.US", "Stock (US)", "FIS", "Fidelity National Information Services Inc", "USD", "US Dollar", "Fidelity National Info Services vs US Dollar"),
        ("FITB.US", "Stock (US)", "FITB", "Fifth Third Bancorp", "USD", "US Dollar", "Fifth Third Bancorp vs US Dollar"),
        ("FLS.US", "Stock (US)", "FLS", "Flowserve Corp", "USD", "US Dollar", "Flowserve Corp vs US Dollar"),
        ("FMC.US", "Stock (US)", "FMC", "FMC Corp", "USD", "US Dollar", "FMC Corp vs US Dollar"),
        ("FOX.US", "Stock (US)", "FOX", "Fox Corp Class B", "USD", "US Dollar", "Fox Corp Class B vs US Dollar"),
        ("FOXA.US", "Stock (US)", "FOXA", "Fox Corp Class A", "USD", "US Dollar", "Fox Corp Class A vs US Dollar"),
        ("FRT.US", "Stock (US)", "FRT", "Federal Realty Investment Trust", "USD", "US Dollar", "Federal Realty Investment Trust vs US Dollar"),
        ("FTNT.US", "Stock (US)", "FTNT", "Fortinet Inc", "USD", "US Dollar", "Fortinet Inc vs US Dollar"),
        ("FTV.US", "Stock (US)", "FTV", "Fortive Corp", "USD", "US Dollar", "Fortive Corp vs US Dollar"),
        ("GAP.US", "Stock (US)", "GAP", "Gap Inc", "USD", "US Dollar", "Gap Inc vs US Dollar"),
        ("GD.US", "Stock (US)", "GD", "General Dynamics Corp", "USD", "US Dollar", "General Dynamics Corp vs US Dollar"),
        ("GE.US", "Stock (US)", "GE", "General Electric Co", "USD", "US Dollar", "General Electric Co vs US Dollar"),
        ("GILD.US", "Stock (US)", "GILD", "Gilead Sciences Inc", "USD", "US Dollar", "Gilead Sciences Inc vs US Dollar"),
        ("GIS.US", "Stock (US)", "GIS", "General Mills Inc", "USD", "US Dollar", "General Mills Inc vs US Dollar"),
        ("GL.US", "Stock (US)", "GL", "Globe Life Inc", "USD", "US Dollar", "Globe Life Inc vs US Dollar"),
        ("GLW.US", "Stock (US)", "GLW", "Corning Inc", "USD", "US Dollar", "Corning Inc vs US Dollar"),
        ("GM.US", "Stock (US)", "GM", "General Motors Co", "USD", "US Dollar", "General Motors Co vs US Dollar"),
        ("GME.US", "Stock (US)", "GME", "GameStop Corp", "USD", "US Dollar", "GameStop Corp vs US Dollar"),
        ("GOOG.US", "Stock (US)", "GOOG", "Alphabet Inc Class C", "USD", "US Dollar", "Alphabet Inc Class C vs US Dollar"),
        ("GOOGL.US", "Stock (US)", "GOOGL", "Alphabet Inc Class A", "USD", "US Dollar", "Alphabet Inc Class A vs US Dollar"),
        ("GPC.US", "Stock (US)", "GPC", "Genuine Parts Co", "USD", "US Dollar", "Genuine Parts Co vs US Dollar"),
        ("GPN.US", "Stock (US)", "GPN", "Global Payments Inc", "USD", "US Dollar", "Global Payments Inc vs US Dollar"),
        ("GPRO.US", "Stock (US)", "GPRO", "GoPro Inc", "USD", "US Dollar", "GoPro Inc vs US Dollar"),
        ("GRMN.US", "Stock (US)", "GRMN", "Garmin Ltd", "USD", "US Dollar", "Garmin Ltd vs US Dollar"),
        ("GS.US", "Stock (US)", "GS", "Goldman Sachs Group Inc", "USD", "US Dollar", "Goldman Sachs Group Inc vs US Dollar"),
        ("GTLB.US", "Stock (US)", "GTLB", "GitLab Inc", "USD", "US Dollar", "GitLab Inc vs US Dollar"),
        ("HAL.US", "Stock (US)", "HAL", "Halliburton Co", "USD", "US Dollar", "Halliburton Co vs US Dollar"),
        ("HAS.US", "Stock (US)", "HAS", "Hasbro Inc", "USD", "US Dollar", "Hasbro Inc vs US Dollar"),
        ("HBAN.US", "Stock (US)", "HBAN", "Huntington Bancshares Inc", "USD", "US Dollar", "Huntington Bancshares Inc vs US Dollar"),
        ("HCA.US", "Stock (US)", "HCA", "HCA Healthcare Inc", "USD", "US Dollar", "HCA Healthcare Inc vs US Dollar"),
        ("HBAR.US", "Stock (US)", "HBAR", "Hedera", "USD", "US Dollar", "Hedera vs US Dollar"),
        ("HIG.US", "Stock (US)", "HIG", "Hartford Financial Services Group Inc", "USD", "US Dollar", "Hartford Financial vs US Dollar"),
        ("HII.US", "Stock (US)", "HII", "Huntington Ingalls Industries Inc", "USD", "US Dollar", "Huntington Ingalls vs US Dollar"),
        ("HLT.US", "Stock (US)", "HLT", "Hilton Worldwide Holdings Inc", "USD", "US Dollar", "Hilton Worldwide vs US Dollar"),
        ("HON.US", "Stock (US)", "HON", "Honeywell International Inc", "USD", "US Dollar", "Honeywell International vs US Dollar"),
        ("HPE.US", "Stock (US)", "HPE", "Hewlett Packard Enterprise Co", "USD", "US Dollar", "Hewlett Packard Enterprise vs US Dollar"),
        ("HPQ.US", "Stock (US)", "HPQ", "HP Inc", "USD", "US Dollar", "HP Inc vs US Dollar"),
        ("HRL.US", "Stock (US)", "HRL", "Hormel Foods Corp", "USD", "US Dollar", "Hormel Foods Corp vs US Dollar"),
        ("HSIC.US", "Stock (US)", "HSIC", "Henry Schein Inc", "USD", "US Dollar", "Henry Schein Inc vs US Dollar"),
        ("HST.US", "Stock (US)", "HST", "Host Hotels & Resorts Inc", "USD", "US Dollar", "Host Hotels & Resorts vs US Dollar"),
        ("HUM.US", "Stock (US)", "HUM", "Humana Inc", "USD", "US Dollar", "Humana Inc vs US Dollar"),
        ("HWM.US", "Stock (US)", "HWM", "Howmet Aerospace Inc", "USD", "US Dollar", "Howmet Aerospace Inc vs US Dollar"),
        ("IBM.US", "Stock (US)", "IBM", "IBM Corp", "USD", "US Dollar", "IBM Corp vs US Dollar"),
        ("ICE.US", "Stock (US)", "ICE", "Intercontinental Exchange Inc", "USD", "US Dollar", "Intercontinental Exchange vs US Dollar"),
        ("IDXX.US", "Stock (US)", "IDXX", "IDEXX Laboratories Inc", "USD", "US Dollar", "IDEXX Laboratories vs US Dollar"),
        ("IEX.US", "Stock (US)", "IEX", "IDEX Corp", "USD", "US Dollar", "IDEX Corp vs US Dollar"),
        ("IFF.US", "Stock (US)", "IFF", "International Flavors & Fragrances Inc", "USD", "US Dollar", "International Flavors & Fragrances vs US Dollar"),
        ("ILMN.US", "Stock (US)", "ILMN", "Illumina Inc", "USD", "US Dollar", "Illumina Inc vs US Dollar"),
        ("INCY.US", "Stock (US)", "INCY", "Incyte Corp", "USD", "US Dollar", "Incyte Corp vs US Dollar"),
        ("INJ.US", "Stock (US)", "INJ", "Injective", "USD", "US Dollar", "Injective vs US Dollar"),
        ("INTC.US", "Stock (US)", "INTC", "Intel Corp", "USD", "US Dollar", "Intel Corp vs US Dollar"),
        ("INTU.US", "Stock (US)", "INTU", "Intuit Inc", "USD", "US Dollar", "Intuit Inc vs US Dollar"),
        ("IPGP.US", "Stock (US)", "IPGP", "IPG Photonics Corp", "USD", "US Dollar", "IPG Photonics Corp vs US Dollar"),
        ("IQV.US", "Stock (US)", "IQV", "IQVIA Holdings Inc", "USD", "US Dollar", "IQVIA Holdings Inc vs US Dollar"),
        ("IRM.US", "Stock (US)", "IRM", "Iron Mountain Inc", "USD", "US Dollar", "Iron Mountain Inc vs US Dollar"),
        ("ISRG.US", "Stock (US)", "ISRG", "Intuitive Surgical Inc", "USD", "US Dollar", "Intuitive Surgical Inc vs US Dollar"),
        ("IT.US", "Stock (US)", "IT", "Gartner Inc", "USD", "US Dollar", "Gartner Inc vs US Dollar"),
        ("ITW.US", "Stock (US)", "ITW", "Illinois Tool Works Inc", "USD", "US Dollar", "Illinois Tool Works vs US Dollar"),
        ("IVZ.US", "Stock (US)", "IVZ", "Invesco Ltd", "USD", "US Dollar", "Invesco Ltd vs US Dollar"),
        ("J.US", "Stock (US)", "J", "Jacobs Solutions Inc", "USD", "US Dollar", "Jacobs Solutions Inc vs US Dollar"),
        ("JBHT.US", "Stock (US)", "JBHT", "J.B. Hunt Transport Services Inc", "USD", "US Dollar", "J.B. Hunt Transport vs US Dollar"),
        ("JCI.US", "Stock (US)", "JCI", "Johnson Controls International plc", "USD", "US Dollar", "Johnson Controls vs US Dollar"),
        ("JEF.US", "Stock (US)", "JEF", "Jefferies Financial Group Inc", "USD", "US Dollar", "Jefferies Financial vs US Dollar"),
        ("JKHY.US", "Stock (US)", "JKHY", "Jack Henry & Associates Inc", "USD", "US Dollar", "Jack Henry & Associates vs US Dollar"),
        ("JNJ.US", "Stock (US)", "JNJ", "Johnson & Johnson", "USD", "US Dollar", "Johnson & Johnson vs US Dollar"),
        ("JPM.US", "Stock (US)", "JPM", "JPMorgan Chase & Co", "USD", "US Dollar", "JPMorgan Chase & Co vs US Dollar"),
        ("JUP.US", "Stock (US)", "JUP", "Jupiter", "USD", "US Dollar", "Jupiter vs US Dollar"),
        ("K.US", "Stock (US)", "K", "Kellogg Co", "USD", "US Dollar", "Kellogg Co vs US Dollar"),
        ("KEY.US", "Stock (US)", "KEY", "KeyCorp", "USD", "US Dollar", "KeyCorp vs US Dollar"),
        ("KEYS.US", "Stock (US)", "KEYS", "Keysight Technologies Inc", "USD", "US Dollar", "Keysight Technologies vs US Dollar"),
        ("KHC.US", "Stock (US)", "KHC", "Kraft Heinz Co", "USD", "US Dollar", "Kraft Heinz Co vs US Dollar"),
        ("KIM.US", "Stock (US)", "KIM", "Kimco Realty Corp", "USD", "US Dollar", "Kimco Realty Corp vs US Dollar"),
        ("KLAC.US", "Stock (US)", "KLAC", "KLA Corp", "USD", "US Dollar", "KLA Corp vs US Dollar"),
        ("KMB.US", "Stock (US)", "KMB", "Kimberly-Clark Corp", "USD", "US Dollar", "Kimberly-Clark Corp vs US Dollar"),
        ("KMI.US", "Stock (US)", "KMI", "Kinder Morgan Inc", "USD", "US Dollar", "Kinder Morgan Inc vs US Dollar"),
        ("KMX.US", "Stock (US)", "KMX", "CarMax Inc", "USD", "US Dollar", "CarMax Inc vs US Dollar"),
        ("KR.US", "Stock (US)", "KR", "Kroger Co", "USD", "US Dollar", "Kroger Co vs US Dollar"),
        ("L.US", "Stock (US)", "L", "Loews Corp", "USD", "US Dollar", "Loews Corp vs US Dollar"),
        ("LCID.US", "Stock (US)", "LCID", "Lucid Group Inc", "USD", "US Dollar", "Lucid Group Inc vs US Dollar"),
        ("LDOS.US", "Stock (US)", "LDOS", "Leidos Holdings Inc", "USD", "US Dollar", "Leidos Holdings Inc vs US Dollar"),
        ("LEG.US", "Stock (US)", "LEG", "Leggett & Platt Inc", "USD", "US Dollar", "Leggett & Platt Inc vs US Dollar"),
        ("LEN.US", "Stock (US)", "LEN", "Lennar Corp", "USD", "US Dollar", "Lennar Corp vs US Dollar"),
        ("LH.US", "Stock (US)", "LH", "Labcorp Holdings Inc", "USD", "US Dollar", "Labcorp Holdings Inc vs US Dollar"),
        ("LHX.US", "Stock (US)", "LHX", "L3Harris Technologies Inc", "USD", "US Dollar", "L3Harris Technologies vs US Dollar"),
        ("LIN.US", "Stock (US)", "LIN", "Linde plc", "USD", "US Dollar", "Linde plc vs US Dollar"),
        ("LKQ.US", "Stock (US)", "LKQ", "LKQ Corp", "USD", "US Dollar", "LKQ Corp vs US Dollar"),
        ("LMT.US", "Stock (US)", "LMT", "Lockheed Martin Corp", "USD", "US Dollar", "Lockheed Martin Corp vs US Dollar"),
        ("LNC.US", "Stock (US)", "LNC", "Lincoln National Corp", "USD", "US Dollar", "Lincoln National Corp vs US Dollar"),
        ("LNT.US", "Stock (US)", "LNT", "Alliant Energy Corp", "USD", "US Dollar", "Alliant Energy Corp vs US Dollar"),
        ("LOGI.US", "Stock (US)", "LOGI", "Logitech International SA", "USD", "US Dollar", "Logitech International vs US Dollar"),
        ("LOW.US", "Stock (US)", "LOW", "Lowe's Companies Inc", "USD", "US Dollar", "Lowe's Companies Inc vs US Dollar"),
        ("LRCX.US", "Stock (US)", "LRCX", "Lam Research Corp", "USD", "US Dollar", "Lam Research Corp vs US Dollar"),
        ("LULU.US", "Stock (US)", "LULU", "Lululemon Athletica Inc", "USD", "US Dollar", "Lululemon Athletica vs US Dollar"),
        ("LUMN.US", "Stock (US)", "LUMN", "Lumen Technologies Inc", "USD", "US Dollar", "Lumen Technologies Inc vs US Dollar"),
        ("LVS.US", "Stock (US)", "LVS", "Las Vegas Sands Corp", "USD", "US Dollar", "Las Vegas Sands Corp vs US Dollar"),
        ("LW.US", "Stock (US)", "LW", "Lamb Weston Holdings Inc", "USD", "US Dollar", "Lamb Weston Holdings vs US Dollar"),
        ("LYB.US", "Stock (US)", "LYB", "LyondellBasell Industries NV", "USD", "US Dollar", "LyondellBasell vs US Dollar"),
        ("LYFT.US", "Stock (US)", "LYFT", "Lyft Inc", "USD", "US Dollar", "Lyft Inc vs US Dollar"),
        ("LYV.US", "Stock (US)", "LYV", "Live Nation Entertainment Inc", "USD", "US Dollar", "Live Nation vs US Dollar"),
        ("MA.US", "Stock (US)", "MA", "Mastercard Inc", "USD", "US Dollar", "Mastercard Inc vs US Dollar"),
        ("MANU.US", "Stock (US)", "MANU", "Manchester United plc", "USD", "US Dollar", "Manchester United vs US Dollar"),
        ("MCD.US", "Stock (US)", "MCD", "McDonald's Corp", "USD", "US Dollar", "McDonald's Corp vs US Dollar"),
        ("META.US", "Stock (US)", "META", "Meta Platforms Inc", "USD", "US Dollar", "Meta Platforms Inc vs US Dollar"),
        ("MMM.US", "Stock (US)", "MMM", "3M Co", "USD", "US Dollar", "3M Co vs US Dollar"),
        ("MO.US", "Stock (US)", "MO", "Altria Group Inc", "USD", "US Dollar", "Altria Group Inc vs US Dollar"),
        ("MRNA.US", "Stock (US)", "MRNA", "Moderna Inc", "USD", "US Dollar", "Moderna Inc vs US Dollar"),
        ("MSFT.US", "Stock (US)", "MSFT", "Microsoft Corp", "USD", "US Dollar", "Microsoft Corp vs US Dollar"),
        ("NFLX.US", "Stock (US)", "NFLX", "Netflix Inc", "USD", "US Dollar", "Netflix Inc vs US Dollar"),
        ("NKE.US", "Stock (US)", "NKE", "Nike Inc", "USD", "US Dollar", "Nike Inc vs US Dollar"),
        ("NVDA.US", "Stock (US)", "NVDA", "NVIDIA Corp", "USD", "US Dollar", "NVIDIA Corp vs US Dollar"),
        ("ONDO.US", "Stock (US)", "ONDO", "Ondo", "USD", "US Dollar", "Ondo vs US Dollar"),
        ("ORCL.US", "Stock (US)", "ORCL", "Oracle Corp", "USD", "US Dollar", "Oracle Corp vs US Dollar"),
        ("PANW.US", "Stock (US)", "PANW", "Palo Alto Networks Inc", "USD", "US Dollar", "Palo Alto Networks Inc vs US Dollar"),
        ("PFE.US", "Stock (US)", "PFE", "Pfizer Inc", "USD", "US Dollar", "Pfizer Inc vs US Dollar"),
        ("PG.US", "Stock (US)", "PG", "Procter & Gamble Co", "USD", "US Dollar", "Procter & Gamble Co vs US Dollar"),
        ("PLTR.US", "Stock (US)", "PLTR", "Palantir Technologies Inc", "USD", "US Dollar", "Palantir Technologies vs US Dollar"),
        ("POL.US", "Stock (US)", "POL", "Polygon", "USD", "US Dollar", "Polygon vs US Dollar"),
        ("PTON.US", "Stock (US)", "PTON", "Peloton Interactive Inc", "USD", "US Dollar", "Peloton Interactive vs US Dollar"),
        ("PYPL.US", "Stock (US)", "PYPL", "PayPal Holdings Inc", "USD", "US Dollar", "PayPal Holdings Inc vs US Dollar"),
        ("QCOM.US", "Stock (US)", "QCOM", "Qualcomm Inc", "USD", "US Dollar", "Qualcomm Inc vs US Dollar"),
        ("RYAAY.US", "Stock (US)", "RYAAY", "Ryanair Holdings plc", "USD", "US Dollar", "Ryanair Holdings plc vs US Dollar"),
        ("SCHW.US", "Stock (US)", "SCHW", "Charles Schwab Corp", "USD", "US Dollar", "Charles Schwab Corp vs US Dollar"),
        ("SHOP.US", "Stock (US)", "SHOP", "Shopify Inc", "USD", "US Dollar", "Shopify Inc vs US Dollar"),
        ("SNAP.US", "Stock (US)", "SNAP", "Snap Inc", "USD", "US Dollar", "Snap Inc vs US Dollar"),
        ("SOL.US", "Stock (US)", "SOL", "Solana", "USD", "US Dollar", "Solana vs US Dollar"),
        ("SPCE.US", "Stock (US)", "SPCE", "Virgin Galactic Holdings Inc", "USD", "US Dollar", "Virgin Galactic vs US Dollar"),
        ("SUI.US", "Stock (US)", "SUI", "Sui", "USD", "US Dollar", "Sui vs US Dollar"),
        ("T.US", "Stock (US)", "T", "AT&T Inc", "USD", "US Dollar", "AT&T Inc vs US Dollar"),
        ("TDOC.US", "Stock (US)", "TDOC", "Teladoc Health Inc", "USD", "US Dollar", "Teladoc Health Inc vs US Dollar"),
        ("TMUS.US", "Stock (US)", "TMUS", "T-Mobile US Inc", "USD", "US Dollar", "T-Mobile US Inc vs US Dollar"),
        ("TON.US", "Stock (US)", "TON", "Toncoin", "USD", "US Dollar", "Toncoin vs US Dollar"),
        ("TRIP.US", "Stock (US)", "TRIP", "TripAdvisor Inc", "USD", "US Dollar", "TripAdvisor Inc vs US Dollar"),
        ("TRUMP.US", "Stock (US)", "TRUMP", "MAGA TRUMP", "USD", "US Dollar", "MAGA TRUMP vs US Dollar"),
        ("TRX.US", "Stock (US)", "TRX", "Tron", "USD", "US Dollar", "Tron vs US Dollar"),
        ("TSLA.US", "Stock (US)", "TSLA", "Tesla Inc", "USD", "US Dollar", "Tesla Inc vs US Dollar"),
        ("TTE.US", "Stock (US)", "TTE", "TotalEnergies SE", "USD", "US Dollar", "TotalEnergies SE vs US Dollar"),
        ("UBER.US", "Stock (US)", "UBER", "Uber Technologies Inc", "USD", "US Dollar", "Uber Technologies Inc vs US Dollar"),
        ("UNI.US", "Stock (US)", "UNI", "Uniswap", "USD", "US Dollar", "Uniswap vs US Dollar"),
        ("V.US", "Stock (US)", "V", "Visa Inc", "USD", "US Dollar", "Visa Inc vs US Dollar"),
        ("WIF.US", "Stock (US)", "WIF", "dogwifhat", "USD", "US Dollar", "dogwifhat vs US Dollar"),
        ("WMT.US", "Stock (US)", "WMT", "Walmart Inc", "USD", "US Dollar", "Walmart Inc vs US Dollar"),
        ("XLM.US", "Stock (US)", "XLM", "Stellar", "USD", "US Dollar", "Stellar vs US Dollar"),
        ("XOM.US", "Stock (US)", "XOM", "Exxon Mobil Corp", "USD", "US Dollar", "Exxon Mobil Corp vs US Dollar"),
        ("XRP.US", "Stock (US)", "XRP", "Ripple", "USD", "US Dollar", "Ripple vs US Dollar"),
        ("XRAY.US", "Stock (US)", "XRAY", "Dentsply Sirona Inc", "USD", "US Dollar", "Dentsply Sirona Inc vs US Dollar"),
        ("ZM.US", "Stock (US)", "ZM", "Zoom Video Communications Inc", "USD", "US Dollar", "Zoom Video vs US Dollar"),
        ("LI.US", "Stock (US)", "LI", "Li Auto Inc", "USD", "US Dollar", "Li Auto Inc vs US Dollar"),
        ("LRN.US", "Stock (US)", "LRN", "Stride Inc", "USD", "US Dollar", "Stride Inc vs US Dollar"),
        ("LSCC.US", "Stock (US)", "LSCC", "Lattice Semiconductor Corp", "USD", "US Dollar", "Lattice Semiconductor vs US Dollar"),
        ("LUV.US", "Stock (US)", "LUV", "Southwest Airlines Co", "USD", "US Dollar", "Southwest Airlines Co vs US Dollar"),
        ("M.US", "Stock (US)", "M", "Macy's Inc", "USD", "US Dollar", "Macy's Inc vs US Dollar"),
        ("MAA.US", "Stock (US)", "MAA", "Mid-America Apartment Communities", "USD", "US Dollar", "Mid-America Apartment vs US Dollar"),
        ("MAR.US", "Stock (US)", "MAR", "Marriott International Inc", "USD", "US Dollar", "Marriott International vs US Dollar"),
        ("MARA.US", "Stock (US)", "MARA", "MARA Holdings Inc", "USD", "US Dollar", "MARA Holdings Inc vs US Dollar"),
        ("MAS.US", "Stock (US)", "MAS", "Masco Corp", "USD", "US Dollar", "Masco Corp vs US Dollar"),
        ("MAT.US", "Stock (US)", "MAT", "Mattel Inc", "USD", "US Dollar", "Mattel Inc vs US Dollar"),
        ("MCHP.US", "Stock (US)", "MCHP", "Microchip Technology Inc", "USD", "US Dollar", "Microchip Technology vs US Dollar"),
        ("MCK.US", "Stock (US)", "MCK", "McKesson Corp", "USD", "US Dollar", "McKesson Corp vs US Dollar"),
        ("MCO.US", "Stock (US)", "MCO", "Moody's Corp", "USD", "US Dollar", "Moody's Corp vs US Dollar"),
        ("MDB.US", "Stock (US)", "MDB", "MongoDB Inc", "USD", "US Dollar", "MongoDB Inc vs US Dollar"),
        ("MDLZ.US", "Stock (US)", "MDLZ", "Mondelez International Inc", "USD", "US Dollar", "Mondelez International vs US Dollar"),
        ("MDT.US", "Stock (US)", "MDT", "Medtronic plc", "USD", "US Dollar", "Medtronic plc vs US Dollar"),
        ("MELI.US", "Stock (US)", "MELI", "MercadoLibre Inc", "USD", "US Dollar", "MercadoLibre Inc vs US Dollar"),
        ("MET.US", "Stock (US)", "MET", "MetLife Inc", "USD", "US Dollar", "MetLife Inc vs US Dollar"),
        ("MGM.US", "Stock (US)", "MGM", "MGM Resorts International", "USD", "US Dollar", "MGM Resorts vs US Dollar"),
        ("MHK.US", "Stock (US)", "MHK", "Mohawk Industries Inc", "USD", "US Dollar", "Mohawk Industries vs US Dollar"),
        ("MKC.US", "Stock (US)", "MKC", "McCormick & Co Inc", "USD", "US Dollar", "McCormick & Co Inc vs US Dollar"),
        ("MKTX.US", "Stock (US)", "MKTX", "MarketAxess Holdings Inc", "USD", "US Dollar", "MarketAxess Holdings vs US Dollar"),
        ("MLM.US", "Stock (US)", "MLM", "Martin Marietta Materials Inc", "USD", "US Dollar", "Martin Marietta vs US Dollar"),
        ("MNST.US", "Stock (US)", "MNST", "Monster Beverage Corp", "USD", "US Dollar", "Monster Beverage vs US Dollar"),
        ("MOH.US", "Stock (US)", "MOH", "Molina Healthcare Inc", "USD", "US Dollar", "Molina Healthcare vs US Dollar"),
        ("MORN.US", "Stock (US)", "MORN", "Morningstar Inc", "USD", "US Dollar", "Morningstar Inc vs US Dollar"),
        ("MOS.US", "Stock (US)", "MOS", "Mosaic Co", "USD", "US Dollar", "Mosaic Co vs US Dollar"),
        ("MPC.US", "Stock (US)", "MPC", "Marathon Petroleum Corp", "USD", "US Dollar", "Marathon Petroleum vs US Dollar"),
        ("MPWR.US", "Stock (US)", "MPWR", "Monolithic Power Systems Inc", "USD", "US Dollar", "Monolithic Power vs US Dollar"),
        ("MRK.US", "Stock (US)", "MRK", "Merck & Co Inc", "USD", "US Dollar", "Merck & Co Inc vs US Dollar"),
        ("MRSH.US", "Stock (US)", "MRSH", "Marsh & McLennan Companies", "USD", "US Dollar", "Marsh & McLennan vs US Dollar"),
        ("MRVL.US", "Stock (US)", "MRVL", "Marvell Technology Inc", "USD", "US Dollar", "Marvell Technology vs US Dollar"),
        ("MS.US", "Stock (US)", "MS", "Morgan Stanley", "USD", "US Dollar", "Morgan Stanley vs US Dollar"),
        ("MSCI.US", "Stock (US)", "MSCI", "MSCI Inc", "USD", "US Dollar", "MSCI Inc vs US Dollar"),
        ("MSI.US", "Stock (US)", "MSI", "Motorola Solutions Inc", "USD", "US Dollar", "Motorola Solutions vs US Dollar"),
        ("MSTR.US", "Stock (US)", "MSTR", "MicroStrategy Inc", "USD", "US Dollar", "MicroStrategy Inc vs US Dollar"),
        ("MTB.US", "Stock (US)", "MTB", "M&T Bank Corp", "USD", "US Dollar", "M&T Bank Corp vs US Dollar"),
        ("MTCH.US", "Stock (US)", "MTCH", "Match Group Inc", "USD", "US Dollar", "Match Group Inc vs US Dollar"),
        ("MTD.US", "Stock (US)", "MTD", "Mettler-Toledo International", "USD", "US Dollar", "Mettler-Toledo vs US Dollar"),
        ("MU.US", "Stock (US)", "MU", "Micron Technology Inc", "USD", "US Dollar", "Micron Technology vs US Dollar"),
        ("NDAQ.US", "Stock (US)", "NDAQ", "Nasdaq Inc", "USD", "US Dollar", "Nasdaq Inc vs US Dollar"),
        ("NDSN.US", "Stock (US)", "NDSN", "Nordson Corp", "USD", "US Dollar", "Nordson Corp vs US Dollar"),
        ("NEE.US", "Stock (US)", "NEE", "NextEra Energy Inc", "USD", "US Dollar", "NextEra Energy Inc vs US Dollar"),
        ("NEM.US", "Stock (US)", "NEM", "Newmont Corp", "USD", "US Dollar", "Newmont Corp vs US Dollar"),
        ("NET.US", "Stock (US)", "NET", "Cloudflare Inc", "USD", "US Dollar", "Cloudflare Inc vs US Dollar"),
        ("NI.US", "Stock (US)", "NI", "NiSource Inc", "USD", "US Dollar", "NiSource Inc vs US Dollar"),
        ("NIO.US", "Stock (US)", "NIO", "NIO Inc", "USD", "US Dollar", "NIO Inc vs US Dollar"),
        ("NNOX.US", "Stock (US)", "NNOX", "Nano-X Imaging Ltd", "USD", "US Dollar", "Nano-X Imaging vs US Dollar"),
        ("NOK.US", "Stock (US)", "NOK", "Nokia Oyj", "USD", "US Dollar", "Nokia Oyj vs US Dollar"),
        ("NOW.US", "Stock (US)", "NOW", "ServiceNow Inc", "USD", "US Dollar", "ServiceNow Inc vs US Dollar"),
        ("NOC.US", "Stock (US)", "NOC", "Northrop Grumman Corp", "USD", "US Dollar", "Northrop Grumman vs US Dollar"),
        ("NOV.US", "Stock (US)", "NOV", "NOV Inc", "USD", "US Dollar", "NOV Inc vs US Dollar"),
        ("NRG.US", "Stock (US)", "NRG", "NRG Energy Inc", "USD", "US Dollar", "NRG Energy Inc vs US Dollar"),
        ("NSA.US", "Stock (US)", "NSA", "National Storage Affiliates Trust", "USD", "US Dollar", "National Storage vs US Dollar"),
        ("NSC.US", "Stock (US)", "NSC", "Norfolk Southern Corp", "USD", "US Dollar", "Norfolk Southern vs US Dollar"),
        ("NTAP.US", "Stock (US)", "NTAP", "NetApp Inc", "USD", "US Dollar", "NetApp Inc vs US Dollar"),
        ("NTRS.US", "Stock (US)", "NTRS", "Northern Trust Corp", "USD", "US Dollar", "Northern Trust vs US Dollar"),
        ("NUE.US", "Stock (US)", "NUE", "Nucor Corp", "USD", "US Dollar", "Nucor Corp vs US Dollar"),
        ("NVAX.US", "Stock (US)", "NVAX", "Novavax Inc", "USD", "US Dollar", "Novavax Inc vs US Dollar"),
        ("NVR.US", "Stock (US)", "NVR", "NVR Inc", "USD", "US Dollar", "NVR Inc vs US Dollar"),
        ("NWL.US", "Stock (US)", "NWL", "Newell Brands Inc", "USD", "US Dollar", "Newell Brands Inc vs US Dollar"),
        ("NWS.US", "Stock (US)", "NWS", "News Corp Class B", "USD", "US Dollar", "News Corp vs US Dollar"),
        ("NWSA.US", "Stock (US)", "NWSA", "News Corp Class A", "USD", "US Dollar", "News Corp vs US Dollar"),
        ("NXPI.US", "Stock (US)", "NXPI", "NXP Semiconductors NV", "USD", "US Dollar", "NXP Semiconductors vs US Dollar"),
        ("NYT.US", "Stock (US)", "NYT", "New York Times Co", "USD", "US Dollar", "New York Times vs US Dollar"),
        ("O.US", "Stock (US)", "O", "Realty Income Corp", "USD", "US Dollar", "Realty Income vs US Dollar"),
        ("ODFL.US", "Stock (US)", "ODFL", "Old Dominion Freight Line", "USD", "US Dollar", "Old Dominion vs US Dollar"),
        ("OKE.US", "Stock (US)", "OKE", "ONEOK Inc", "USD", "US Dollar", "ONEOK Inc vs US Dollar"),
        ("OMC.US", "Stock (US)", "OMC", "Omnicom Group Inc", "USD", "US Dollar", "Omnicom Group vs US Dollar"),
        ("ON.US", "Stock (US)", "ON", "ON Semiconductor Corp", "USD", "US Dollar", "ON Semiconductor vs US Dollar"),
        ("ORLY.US", "Stock (US)", "ORLY", "O'Reilly Automotive Inc", "USD", "US Dollar", "O'Reilly Automotive vs US Dollar"),
        ("OTIS.US", "Stock (US)", "OTIS", "Otis Worldwide Corp", "USD", "US Dollar", "Otis Worldwide vs US Dollar"),
        ("OXY.US", "Stock (US)", "OXY", "Occidental Petroleum Corp", "USD", "US Dollar", "Occidental Petroleum vs US Dollar"),
        ("PATH.US", "Stock (US)", "PATH", "UiPath Inc", "USD", "US Dollar", "UiPath Inc vs US Dollar"),
        ("PAYC.US", "Stock (US)", "PAYC", "Paycom Software Inc", "USD", "US Dollar", "Paycom Software vs US Dollar"),
        ("PAYX.US", "Stock (US)", "PAYX", "Paychex Inc", "USD", "US Dollar", "Paychex Inc vs US Dollar"),
        ("PCAR.US", "Stock (US)", "PCAR", "PACCAR Inc", "USD", "US Dollar", "PACCAR Inc vs US Dollar"),
        ("PCG.US", "Stock (US)", "PCG", "PG&E Corp", "USD", "US Dollar", "PG&E Corp vs US Dollar"),
        ("PD.US", "Stock (US)", "PD", "PagerDuty Inc", "USD", "US Dollar", "PagerDuty Inc vs US Dollar"),
        ("PEG.US", "Stock (US)", "PEG", "Public Service Enterprise Group", "USD", "US Dollar", "Public Service Group vs US Dollar"),
        ("PFG.US", "Stock (US)", "PFG", "Principal Financial Group", "USD", "US Dollar", "Principal Financial vs US Dollar"),
        ("PGR.US", "Stock (US)", "PGR", "Progressive Corp", "USD", "US Dollar", "Progressive Corp vs US Dollar"),
        ("PH.US", "Stock (US)", "PH", "Parker-Hannifin Corp", "USD", "US Dollar", "Parker-Hannifin vs US Dollar"),
        ("PHM.US", "Stock (US)", "PHM", "PulteGroup Inc", "USD", "US Dollar", "PulteGroup Inc vs US Dollar"),
        ("PINS.US", "Stock (US)", "PINS", "Pinterest Inc", "USD", "US Dollar", "Pinterest Inc vs US Dollar"),
        ("PKG.US", "Stock (US)", "PKG", "Packaging Corp of America", "USD", "US Dollar", "Packaging Corp vs US Dollar"),
        ("PLD.US", "Stock (US)", "PLD", "Prologis Inc", "USD", "US Dollar", "Prologis Inc vs US Dollar"),
        ("PM.US", "Stock (US)", "PM", "Philip Morris International", "USD", "US Dollar", "Philip Morris vs US Dollar"),
        ("PNC.US", "Stock (US)", "PNC", "PNC Financial Services Group", "USD", "US Dollar", "PNC Financial vs US Dollar"),
        ("PNR.US", "Stock (US)", "PNR", "Pentair plc", "USD", "US Dollar", "Pentair plc vs US Dollar"),
        ("PNW.US", "Stock (US)", "PNW", "Pinnacle West Capital Corp", "USD", "US Dollar", "Pinnacle West vs US Dollar"),
        ("PODD.US", "Stock (US)", "PODD", "Insulet Corp", "USD", "US Dollar", "Insulet Corp vs US Dollar"),
        ("POOL.US", "Stock (US)", "POOL", "Pool Corp", "USD", "US Dollar", "Pool Corp vs US Dollar"),
        ("PPG.US", "Stock (US)", "PPG", "PPG Industries Inc", "USD", "US Dollar", "PPG Industries vs US Dollar"),
        ("PPL.US", "Stock (US)", "PPL", "PPL Corp", "USD", "US Dollar", "PPL Corp vs US Dollar"),
        ("PRGO.US", "Stock (US)", "PRGO", "Perrigo Company plc", "USD", "US Dollar", "Perrigo Company vs US Dollar"),
        ("PRU.US", "Stock (US)", "PRU", "Prudential Financial Inc", "USD", "US Dollar", "Prudential Financial vs US Dollar"),
        ("PSA.US", "Stock (US)", "PSA", "Public Storage", "USD", "US Dollar", "Public Storage vs US Dollar"),
        ("PSX.US", "Stock (US)", "PSX", "Phillips 66", "USD", "US Dollar", "Phillips 66 vs US Dollar"),
        ("PTC.US", "Stock (US)", "PTC", "PTC Inc", "USD", "US Dollar", "PTC Inc vs US Dollar"),
        ("PTEN.US", "Stock (US)", "PTEN", "Patterson-UTI Energy Inc", "USD", "US Dollar", "Patterson-UTI vs US Dollar"),
        ("PWR.US", "Stock (US)", "PWR", "Quanta Services Inc", "USD", "US Dollar", "Quanta Services vs US Dollar"),
        ("PZZA.US", "Stock (US)", "PZZA", "Papa John's International", "USD", "US Dollar", "Papa John's vs US Dollar"),
        ("REG.US", "Stock (US)", "REG", "Regency Centers Corp", "USD", "US Dollar", "Regency Centers vs US Dollar"),
        ("REGN.US", "Stock (US)", "REGN", "Regeneron Pharmaceuticals", "USD", "US Dollar", "Regeneron vs US Dollar"),
        ("RF.US", "Stock (US)", "RF", "Regions Financial Corp", "USD", "US Dollar", "Regions Financial vs US Dollar"),
        ("RIOT.US", "Stock (US)", "RIOT", "Riot Platforms Inc", "USD", "US Dollar", "Riot Platforms Inc vs US Dollar"),
        ("RIVN.US", "Stock (US)", "RIVN", "Rivian Automotive Inc", "USD", "US Dollar", "Rivian Automotive vs US Dollar"),
        ("RJF.US", "Stock (US)", "RJF", "Raymond James Financial", "USD", "US Dollar", "Raymond James vs US Dollar"),
        ("RKLB.US", "Stock (US)", "RKLB", "Rocket Lab USA Inc", "USD", "US Dollar", "Rocket Lab vs US Dollar"),
        ("RL.US", "Stock (US)", "RL", "Ralph Lauren Corp", "USD", "US Dollar", "Ralph Lauren vs US Dollar"),
        ("ROK.US", "Stock (US)", "ROK", "Rockwell Automation Inc", "USD", "US Dollar", "Rockwell Automation vs US Dollar"),
        ("ROL.US", "Stock (US)", "ROL", "Rollins Inc", "USD", "US Dollar", "Rollins Inc vs US Dollar"),
        ("ROP.US", "Stock (US)", "ROP", "Roper Technologies Inc", "USD", "US Dollar", "Roper Technologies vs US Dollar"),
        ("ROST.US", "Stock (US)", "ROST", "Ross Stores Inc", "USD", "US Dollar", "Ross Stores vs US Dollar"),
        ("RSG.US", "Stock (US)", "RSG", "Republic Services Inc", "USD", "US Dollar", "Republic Services vs US Dollar"),
        ("RTX.US", "Stock (US)", "RTX", "RTX Corp", "USD", "US Dollar", "RTX Corp vs US Dollar"),
        ("RVTY.US", "Stock (US)", "RVTY", "Revvity Inc", "USD", "US Dollar", "Revvity Inc vs US Dollar"),
        ("SBAC.US", "Stock (US)", "SBAC", "SBA Communications Corp", "USD", "US Dollar", "SBA Communications vs US Dollar"),
        ("SBUX.US", "Stock (US)", "SBUX", "Starbucks Corp", "USD", "US Dollar", "Starbucks Corp vs US Dollar"),
        ("SE.US", "Stock (US)", "SE", "Sea Ltd", "USD", "US Dollar", "Sea Ltd vs US Dollar"),
        ("SHAK.US", "Stock (US)", "SHAK", "Shake Shack Inc", "USD", "US Dollar", "Shake Shack Inc vs US Dollar"),
        ("SHOO.US", "Stock (US)", "SHOO", "Steven Madden Ltd", "USD", "US Dollar", "Steven Madden Ltd vs US Dollar"),
        ("SHW.US", "Stock (US)", "SHW", "Sherwin-Williams Co", "USD", "US Dollar", "Sherwin-Williams vs US Dollar"),
        ("SIRI.US", "Stock (US)", "SIRI", "Sirius XM Holdings Inc", "USD", "US Dollar", "Sirius XM vs US Dollar"),
        ("SLB.US", "Stock (US)", "SLB", "Schlumberger NV", "USD", "US Dollar", "Schlumberger NV vs US Dollar"),
        ("SMCI.US", "Stock (US)", "SMCI", "Super Micro Computer Inc", "USD", "US Dollar", "Super Micro vs US Dollar"),
        ("SNA.US", "Stock (US)", "SNA", "Snap-on Inc", "USD", "US Dollar", "Snap-on Inc vs US Dollar"),
        ("SNEX.US", "Stock (US)", "SNEX", "StoneX Group Inc", "USD", "US Dollar", "StoneX Group Inc vs US Dollar"),
        ("SNOW.US", "Stock (US)", "SNOW", "Snowflake Inc", "USD", "US Dollar", "Snowflake Inc vs US Dollar"),
        ("SNPS.US", "Stock (US)", "SNPS", "Synopsys Inc", "USD", "US Dollar", "Synopsys Inc vs US Dollar"),
        ("SO.US", "Stock (US)", "SO", "Southern Co", "USD", "US Dollar", "Southern Co vs US Dollar"),
        ("SOLV.US", "Stock (US)", "SOLV", "Solventum Corp", "USD", "US Dollar", "Solventum Corp vs US Dollar"),
        ("SPG.US", "Stock (US)", "SPG", "Simon Property Group Inc", "USD", "US Dollar", "Simon Property vs US Dollar"),
        ("SPGI.US", "Stock (US)", "SPGI", "S&P Global Inc", "USD", "US Dollar", "S&P Global Inc vs US Dollar"),
        ("STE.US", "Stock (US)", "STE", "STERIS plc", "USD", "US Dollar", "STERIS plc vs US Dollar"),
        ("STLD.US", "Stock (US)", "STLD", "Steel Dynamics Inc", "USD", "US Dollar", "Steel Dynamics vs US Dollar"),
        ("STNE.US", "Stock (US)", "STNE", "StoneCo Ltd", "USD", "US Dollar", "StoneCo Ltd vs US Dollar"),
        ("STT.US", "Stock (US)", "STT", "State Street Corp", "USD", "US Dollar", "State Street Corp vs US Dollar"),
        ("STX.US", "Stock (US)", "STX", "Seagate Technology Holdings", "USD", "US Dollar", "Seagate Technology vs US Dollar"),
        ("SW.US", "Stock (US)", "SW", "Smurfit Westrock plc", "USD", "US Dollar", "Smurfit Westrock vs US Dollar"),
        ("SWK.US", "Stock (US)", "SWK", "Stanley Black & Decker Inc", "USD", "US Dollar", "Stanley Black & Decker vs US Dollar"),
        ("SWKS.US", "Stock (US)", "SWKS", "Skyworks Solutions Inc", "USD", "US Dollar", "Skyworks Solutions vs US Dollar"),
        ("SYF.US", "Stock (US)", "SYF", "Synchrony Financial", "USD", "US Dollar", "Synchrony Financial vs US Dollar"),
        ("SYK.US", "Stock (US)", "SYK", "Stryker Corp", "USD", "US Dollar", "Stryker Corp vs US Dollar"),
        ("SYY.US", "Stock (US)", "SYY", "Sysco Corp", "USD", "US Dollar", "Sysco Corp vs US Dollar"),
        ("TGT.US", "Stock (US)", "TGT", "Target Corp", "USD", "US Dollar", "Target Corp vs US Dollar"),
        ("TDG.US", "Stock (US)", "TDG", "TransDigm Group Inc", "USD", "US Dollar", "TransDigm Group vs US Dollar"),
        ("TDY.US", "Stock (US)", "TDY", "Teledyne Technologies Inc", "USD", "US Dollar", "Teledyne vs US Dollar"),
        ("TECH.US", "Stock (US)", "TECH", "Bio-Techne Corp", "USD", "US Dollar", "Bio-Techne Corp vs US Dollar"),
        ("TEL.US", "Stock (US)", "TEL", "TE Connectivity Ltd", "USD", "US Dollar", "TE Connectivity vs US Dollar"),
        ("TER.US", "Stock (US)", "TER", "Teradyne Inc", "USD", "US Dollar", "Teradyne Inc vs US Dollar"),
        ("TFC.US", "Stock (US)", "TFC", "Truist Financial Corp", "USD", "US Dollar", "Truist Financial vs US Dollar"),
        ("TJX.US", "Stock (US)", "TJX", "TJX Companies Inc", "USD", "US Dollar", "TJX Companies vs US Dollar"),
        ("TLRY.US", "Stock (US)", "TLRY", "Tilray Brands Inc", "USD", "US Dollar", "Tilray Brands Inc vs US Dollar"),
        ("TMO.US", "Stock (US)", "TMO", "Thermo Fisher Scientific Inc", "USD", "US Dollar", "Thermo Fisher vs US Dollar"),
        ("TOST.US", "Stock (US)", "TOST", "Toast Inc", "USD", "US Dollar", "Toast Inc vs US Dollar"),
        ("TPR.US", "Stock (US)", "TPR", "Tapestry Inc", "USD", "US Dollar", "Tapestry Inc vs US Dollar"),
        ("TRGP.US", "Stock (US)", "TRGP", "Targa Resources Corp", "USD", "US Dollar", "Targa Resources vs US Dollar"),
        ("TRMB.US", "Stock (US)", "TRMB", "Trimble Inc", "USD", "US Dollar", "Trimble Inc vs US Dollar"),
        ("TROW.US", "Stock (US)", "TROW", "T. Rowe Price Group Inc", "USD", "US Dollar", "T. Rowe Price vs US Dollar"),
        ("TRV.US", "Stock (US)", "TRV", "Travelers Companies Inc", "USD", "US Dollar", "Travelers vs US Dollar"),
        ("TSCO.US", "Stock (US)", "TSCO", "Tractor Supply Co", "USD", "US Dollar", "Tractor Supply vs US Dollar"),
        ("TSM.US", "Stock (US)", "TSM", "Taiwan Semiconductor Manufacturing", "USD", "US Dollar", "TSM vs US Dollar"),
        ("TSN.US", "Stock (US)", "TSN", "Tyson Foods Inc", "USD", "US Dollar", "Tyson Foods Inc vs US Dollar"),
        ("TT.US", "Stock (US)", "TT", "Trane Technologies plc", "USD", "US Dollar", "Trane Technologies vs US Dollar"),
        ("TTD.US", "Stock (US)", "TTD", "The Trade Desk Inc", "USD", "US Dollar", "The Trade Desk vs US Dollar"),
        ("TTWO.US", "Stock (US)", "TTWO", "Take-Two Interactive", "USD", "US Dollar", "Take-Two Interactive vs US Dollar"),
        ("TXN.US", "Stock (US)", "TXN", "Texas Instruments Inc", "USD", "US Dollar", "Texas Instruments vs US Dollar"),
        ("TXT.US", "Stock (US)", "TXT", "Textron Inc", "USD", "US Dollar", "Textron Inc vs US Dollar"),
        ("TYL.US", "Stock (US)", "TYL", "Tyler Technologies Inc", "USD", "US Dollar", "Tyler Technologies vs US Dollar"),
        ("U.US", "Stock (US)", "U", "Unity Software Inc", "USD", "US Dollar", "Unity Software Inc vs US Dollar"),
        ("UA.US", "Stock (US)", "UA", "Under Armour Inc Class C", "USD", "US Dollar", "Under Armour Class C vs US Dollar"),
        ("UAA.US", "Stock (US)", "UAA", "Under Armour Inc Class A", "USD", "US Dollar", "Under Armour Class A vs US Dollar"),
        ("UAL.US", "Stock (US)", "UAL", "United Airlines Holdings", "USD", "US Dollar", "United Airlines vs US Dollar"),
        ("UDR.US", "Stock (US)", "UDR", "UDR Inc", "USD", "US Dollar", "UDR Inc vs US Dollar"),
        ("UNH.US", "Stock (US)", "UNH", "UnitedHealth Group Inc", "USD", "US Dollar", "UnitedHealth Group vs US Dollar"),
        ("UNP.US", "Stock (US)", "UNP", "Union Pacific Corp", "USD", "US Dollar", "Union Pacific vs US Dollar"),
        ("UPS.US", "Stock (US)", "UPS", "United Parcel Service Inc", "USD", "US Dollar", "United Parcel Service vs US Dollar"),
        ("UPST.US", "Stock (US)", "UPST", "Upstart Holdings Inc", "USD", "US Dollar", "Upstart Holdings vs US Dollar"),
        ("URBN.US", "Stock (US)", "URBN", "Urban Outfitters Inc", "USD", "US Dollar", "Urban Outfitters vs US Dollar"),
        ("URI.US", "Stock (US)", "URI", "United Rentals Inc", "USD", "US Dollar", "United Rentals vs US Dollar"),
        ("VLO.US", "Stock (US)", "VLO", "Valero Energy Corp", "USD", "US Dollar", "Valero Energy vs US Dollar"),
        ("VLTO.US", "Stock (US)", "VLTO", "Veralto Corp", "USD", "US Dollar", "Veralto Corp vs US Dollar"),
        ("VMC.US", "Stock (US)", "VMC", "Vulcan Materials Co", "USD", "US Dollar", "Vulcan Materials vs US Dollar"),
        ("VRSK.US", "Stock (US)", "VRSK", "Verisk Analytics Inc", "USD", "US Dollar", "Verisk Analytics vs US Dollar"),
        ("VRSN.US", "Stock (US)", "VRSN", "VeriSign Inc", "USD", "US Dollar", "VeriSign Inc vs US Dollar"),
        ("VRT.US", "Stock (US)", "VRT", "Vertiv Holdings Co", "USD", "US Dollar", "Vertiv Holdings vs US Dollar"),
        ("VRTX.US", "Stock (US)", "VRTX", "Vertex Pharmaceuticals", "USD", "US Dollar", "Vertex Pharmaceuticals vs US Dollar"),
        ("VSCO.US", "Stock (US)", "VSCO", "Victoria's Secret & Co", "USD", "US Dollar", "Victoria's Secret vs US Dollar"),
        ("VST.US", "Stock (US)", "VST", "Vistra Corp", "USD", "US Dollar", "Vistra Corp vs US Dollar"),
        ("VTR.US", "Stock (US)", "VTR", "Ventas Inc", "USD", "US Dollar", "Ventas Inc vs US Dollar"),
        ("VTRS.US", "Stock (US)", "VTRS", "Viatris Inc", "USD", "US Dollar", "Viatris Inc vs US Dollar"),
        ("VZ.US", "Stock (US)", "VZ", "Verizon Communications Inc", "USD", "US Dollar", "Verizon Communications vs US Dollar"),
        ("W.US", "Stock (US)", "W", "Wayfair Inc", "USD", "US Dollar", "Wayfair Inc vs US Dollar"),
        ("WAB.US", "Stock (US)", "WAB", "Wabtec Corp", "USD", "US Dollar", "Wabtec Corp vs US Dollar"),
        ("WAT.US", "Stock (US)", "WAT", "Waters Corp", "USD", "US Dollar", "Waters Corp vs US Dollar"),
        ("WB.US", "Stock (US)", "WB", "Weibo Corp", "USD", "US Dollar", "Weibo Corp vs US Dollar"),
        ("WBD.US", "Stock (US)", "WBD", "Warner Bros. Discovery Inc", "USD", "US Dollar", "Warner Bros Discovery vs US Dollar"),
        ("WDC.US", "Stock (US)", "WDC", "Western Digital Corp", "USD", "US Dollar", "Western Digital vs US Dollar"),
        ("WDAY.US", "Stock (US)", "WDAY", "Workday Inc", "USD", "US Dollar", "Workday Inc vs US Dollar"),
        ("WEC.US", "Stock (US)", "WEC", "WEC Energy Group Inc", "USD", "US Dollar", "WEC Energy Group vs US Dollar"),
        ("WELL.US", "Stock (US)", "WELL", "Welltower Inc", "USD", "US Dollar", "Welltower Inc vs US Dollar"),
        ("WFC.US", "Stock (US)", "WFC", "Wells Fargo & Co", "USD", "US Dollar", "Wells Fargo & Co vs US Dollar"),
        ("WH.US", "Stock (US)", "WH", "Wyndham Hotels & Resorts", "USD", "US Dollar", "Wyndham Hotels vs US Dollar"),
        ("WIX.US", "Stock (US)", "WIX", "Wix.com Ltd", "USD", "US Dollar", "Wix.com Ltd vs US Dollar"),
        ("WM.US", "Stock (US)", "WM", "Waste Management Inc", "USD", "US Dollar", "Waste Management vs US Dollar"),
        ("WMB.US", "Stock (US)", "WMB", "Williams Companies Inc", "USD", "US Dollar", "Williams Companies vs US Dollar"),
        ("WMG.US", "Stock (US)", "WMG", "Warner Music Group Corp", "USD", "US Dollar", "Warner Music Group vs US Dollar"),
        ("WRB.US", "Stock (US)", "WRB", "W. R. Berkley Corp", "USD", "US Dollar", "W. R. Berkley Corp vs US Dollar"),
        ("WST.US", "Stock (US)", "WST", "West Pharmaceutical Services", "USD", "US Dollar", "West Pharmaceutical vs US Dollar"),
        ("WTW.US", "Stock (US)", "WTW", "Willis Towers Watson plc", "USD", "US Dollar", "Willis Towers Watson vs US Dollar"),
        ("WU.US", "Stock (US)", "WU", "Western Union Co", "USD", "US Dollar", "Western Union Co vs US Dollar"),
        ("WY.US", "Stock (US)", "WY", "Weyerhaeuser Co", "USD", "US Dollar", "Weyerhaeuser Co vs US Dollar"),
        ("WYNN.US", "Stock (US)", "WYNN", "Wynn Resorts Ltd", "USD", "US Dollar", "Wynn Resorts Ltd vs US Dollar"),
        ("XEL.US", "Stock (US)", "XEL", "Xcel Energy Inc", "USD", "US Dollar", "Xcel Energy Inc vs US Dollar"),
        ("XPEV.US", "Stock (US)", "XPEV", "XPeng Inc", "USD", "US Dollar", "XPeng Inc vs US Dollar"),
        ("XRX.US", "Stock (US)", "XRX", "Xerox Holdings Corp", "USD", "US Dollar", "Xerox Holdings vs US Dollar"),
        ("XYL.US", "Stock (US)", "XYL", "Xylem Inc", "USD", "US Dollar", "Xylem Inc vs US Dollar"),
        ("YELP.US", "Stock (US)", "YELP", "Yelp Inc", "USD", "US Dollar", "Yelp Inc vs US Dollar"),
        ("YUM.US", "Stock (US)", "YUM", "Yum! Brands Inc", "USD", "US Dollar", "Yum! Brands Inc vs US Dollar"),
        ("Z.US", "Stock (US)", "Z", "Zillow Group Inc Class C", "USD", "US Dollar", "Zillow Group vs US Dollar"),
        ("ZBH.US", "Stock (US)", "ZBH", "Zimmer Biomet Holdings Inc", "USD", "US Dollar", "Zimmer Biomet vs US Dollar"),
        ("ZBRA.US", "Stock (US)", "ZBRA", "Zebra Technologies Corp", "USD", "US Dollar", "Zebra Technologies vs US Dollar"),
        ("GEV.US", "Stock (US)", "GEV", "GE Vernova Inc", "USD", "US Dollar", "GE Vernova Inc vs US Dollar"),
        ("GRAB.US", "Stock (US)", "GRAB", "Grab Holdings Ltd", "USD", "US Dollar", "Grab Holdings Ltd vs US Dollar"),
        ("CRWV.US", "Stock (US)", "CRWV", "CoreWeave Inc", "USD", "US Dollar", "CoreWeave Inc vs US Dollar"),
        ("CORZ.US", "Stock (US)", "CORZ", "Core Scientific Inc", "USD", "US Dollar", "Core Scientific Inc vs US Dollar"),
        ("IREN.US", "Stock (US)", "IREN", "Iris Energy Ltd", "USD", "US Dollar", "Iris Energy Ltd vs US Dollar"),
        ("HUT.US", "Stock (US)", "HUT", "Hut 8 Corp", "USD", "US Dollar", "Hut 8 Corp vs US Dollar"),
        ("GLXY.US", "Stock (US)", "GLXY", "Galaxy Digital Holdings Ltd", "USD", "US Dollar", "Galaxy Digital Holdings Ltd vs US Dollar"),
        ("BITF.US", "Stock (US)", "BITF", "Bitfarms Ltd", "USD", "US Dollar", "Bitfarms Ltd vs US Dollar"),
        ("CVNA.US", "Stock (US)", "CVNA", "Carvana Co", "USD", "US Dollar", "Carvana Co vs US Dollar"),
        ("CLSK.US", "Stock (US)", "CLSK", "CleanSpark Inc", "USD", "US Dollar", "CleanSpark Inc vs US Dollar"),
        ("SOFI.US", "Stock (US)", "SOFI", "SoFi Technologies Inc", "USD", "US Dollar", "SoFi Technologies Inc vs US Dollar"),
        ("UWMC.US", "Stock (US)", "UWMC", "UWM Holdings Corp", "USD", "US Dollar", "UWM Holdings Corp vs US Dollar"),
        ("DUOL.US", "Stock (US)", "DUOL", "Duolingo Inc", "USD", "US Dollar", "Duolingo Inc vs US Dollar"),
        ("PAAS.US", "Stock (US)", "PAAS", "Pan American Silver Corp", "USD", "US Dollar", "Pan American Silver Corp vs US Dollar"),
        ("HL.US", "Stock (US)", "HL", "Hecla Mining Co", "USD", "US Dollar", "Hecla Mining Co vs US Dollar"),
        ("CDE.US", "Stock (US)", "CDE", "Coeur Mining Inc", "USD", "US Dollar", "Coeur Mining Inc vs US Dollar"),
        ("AG.US", "Stock (US)", "AG", "First Majestic Silver Corp", "USD", "US Dollar", "First Majestic Silver Corp vs US Dollar"),
        ("AGI.US", "Stock (US)", "AGI", "Alamos Gold Inc", "USD", "US Dollar", "Alamos Gold Inc vs US Dollar"),
        ("LMND.US", "Stock (US)", "LMND", "Lemonade Inc", "USD", "US Dollar", "Lemonade Inc vs US Dollar"),
        ("NVO.US", "Stock (US)", "NVO", "Novo Nordisk A/S", "USD", "US Dollar", "Novo Nordisk A/S vs US Dollar"),
        ("SPOT.US", "Stock (US)", "SPOT", "Spotify Technology SA", "USD", "US Dollar", "Spotify Technology SA vs US Dollar")
    ]
    etf_data = [
        ("QQQ.US", "ETF (US)", "QQQ", "Invesco QQQ Trust", "USD", "US Dollar", "Invesco QQQ Trust vs US Dollar"),
        ("SPY.US", "ETF (US)", "SPY", "SPDR S&P 500 ETF Trust", "USD", "US Dollar", "SPDR S&P 500 ETF Trust vs US Dollar"),
        ("UNG.US", "ETF (US)", "UNG", "United States Natural Gas Fund", "USD", "US Dollar", "US Natural Gas Fund vs US Dollar"),
        ("USO.US", "ETF (US)", "USO", "United States Oil Fund LP", "USD", "US Dollar", "US Oil Fund vs US Dollar")
    ]
    provider_uid = f"Spotware ({Platform.cTrader.name})"
    for uid, cat, base_asset, base_name, quote_asset, quote_name, desc in forex_data + index_data + crypto_data + metal_data + energy_data + stock_data + etf_data:
        ticker = TickerAPI(UID=uid, Category=cat, BaseAsset=base_asset, BaseName=base_name, QuoteAsset=quote_asset, QuoteName=quote_name, Description=desc, db=db)
        ticker.push(by=by)
        inst = TickerAPI.detect(uid)
        contract = ContractAPI(TickerUID=uid, ProviderUID=provider_uid, Instrument=inst, db=db)
        contract.push(by=by)
        sec = SecurityAPI(ProviderUID=provider_uid, CategoryUID=cat, TickerUID=uid, Instrument=inst, db=db)
        sec.push(by=by)
    timeframes = [
        "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M15", "M20", "M30", "M45",
        "H1", "H2", "H3", "H4", "H6", "H8", "H12",
        "D1", "D2", "D3",
        "W1",
        "MN1"
    ]
    for tf in timeframes:
        t = TimeframeAPI(UID=tf, db=db)
        t.push(by=by)
